### ISSUE TITLE
[Feature Request]回应验证消息

### ISSUE THREAD

**Issue by BoBppy** [SAGIRI-kawaii/sagiri-bot#103]
例如加好友验证消息，拉入群验证消息

、、、
主人主人，有个人来加我好友啦！
ID：599****
来自：xxx
描述：
source：60246***
、、、

希望添加 主人可在私聊页面回应此类请求（

**Comment by nullqwertyuiop** [comment]
实现效果如图，再测试一段时间后 PR
![5bff023baa61646a.jpg](https://user-images.githubusercontent.com/49110142/150635473-aac0d210-613d-4504-ae5f-3a26f9420bf6.jpg)
![2352640335a234fd.jpg](https://user-images.githubusercontent.com/49110142/150635476-7d811cd6-820b-4bc3-a99a-842e12aeff55.jpg)
