### ISSUE TITLE
小白建议 

### ISSUE THREAD

**Issue by 1529960009** [SAGIRI-kawaii/sagiri-bot#116]
![QQ截图20210814180646](https://user-images.githubusercontent.com/45947734/129442636-f3afb15c-b512-4fd7-b1d8-4590309a90e3.png)

mirai 和api都弄了

是数据库没弄好还是啥，大佬可以给一个参考文件么

**Comment by SAGIRI-kawaii** [comment]
报错写了，依赖没装全

**Comment by 1529960009** [comment]
![image](https://user-images.githubusercontent.com/45947734/129443261-062e39fa-9604-40cf-bd79-8b95c0a9a5c7.png)
直接pip install 安装的鸭 也没看到有啥红色报错

**Comment by SAGIRI-kawaii** [comment]
pip install -U graia-saya==0.0.8

**Comment by 1529960009** [comment]
![image](https://user-images.githubusercontent.com/45947734/129444359-b829caf2-7c41-4386-a48a-ca9393a9073d.png)

**Comment by 1529960009** [comment]
![image](https://user-images.githubusercontent.com/45947734/129454305-96c1a0e7-7629-4fad-b39d-385aa65bd936.png)
直接安装requirements的依赖的上面的命令也弄了

**Comment by SAGIRI-kawaii** [comment]
更新graiax-silkcoder
顺便，alembic.ini的连接写错了，应该是 sqlite:///data.db
