### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by 1529960009** [SAGIRI-kawaii/sagiri-bot#119]
![image](https://user-images.githubusercontent.com/45947734/129717560-3de6bada-5b67-4bae-85de-915abce989a3.png)
这些设置好的关键词是啥，是要自己去修改配置文件么，还是其他啥命令
![image](https://user-images.githubusercontent.com/45947734/129717759-0ecfd016-3be5-4350-9a30-5a6f68bafe57.png)

**Comment by nullqwertyuiop** [comment]
添加功能关键词#bizhi#关键词

bizhi可以换为setu或real

**Comment by 1529960009** [comment]
这些设定的实际触发命令是啥

**Comment by nullqwertyuiop** [comment]
> 添加功能关键词#bizhi#关键词
> 
> bizhi可以换为setu或real

就是这条

**Comment by nullqwertyuiop** [comment]
记得 close issue（

**Comment by 1529960009** [comment]
![image](https://user-images.githubusercontent.com/45947734/129723712-6cc112ad-c097-49fc-b2dc-bdcc66b53996.png)

**Comment by SAGIRI-kawaii** [comment]
重复的关键词，数据库中已有此关键词，之后会更改提醒方式

**Comment by SAGIRI-kawaii** [comment]
fixed
