### ISSUE TITLE
[Bug Report]搜番仍存在bug

### ISSUE THREAD

**Issue by BoBppy** [SAGIRI-kawaii/sagiri-bot#121]
**环境信息**

系统版本: win8.1
源码版本:  f9eed01564c27b72938dcea208294c0ba8a3a6b6
其他信息:

**问题描述**
发生了什么情况？有什么现状？是否可复现？

之前是接收图片后报错，现在是接收指令后报错（

**日志**

点击文本框下面小长条可以上传文件

[搜番.txt](https://github.com/SAGIRI-kawaii/sagiri-bot/files/7003864/default.txt)

**Comment by nullqwertyuiop** [comment]
saucenao 也有番剧的数据库
发送请求加个 `&db=21` (SFW) 或 `&db=22` (NSFW) 就行了
准确度没测试（
