### ISSUE TITLE
[Feature Request]无限防撤回制

### ISSUE THREAD

**Issue by BoBppy** [SAGIRI-kawaii/sagiri-bot#122]
**原因**
为什么想要这个功能
今天看他们聊天突发奇想
**功能简述**
想要个怎样的功能
群管理撤回机器人发出的防撤回信息时，机器人不能再次发出已撤回消息

**功能逻辑**
如何交互、如何使用等
建议加个功能(并且有开关)，使能够再次发出已撤回消息，最好可以有群管理控制(但是目前的权限系统并不能使管理员有权限（

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的实例等

感觉应该不会写(doge)

**Comment by SAGIRI-kawaii** [comment]
会被管理员讨厌的（

**Comment by SAGIRI-kawaii** [comment]
遇到一些非法或者反动消息的时候如果没有管理在场就危（

**Comment by nullqwertyuiop** [comment]
会暴毙的，我机器人已经被冻一天了（）
