### ISSUE TITLE
[Feature Request]响应戳一戳

### ISSUE THREAD

**Issue by BoBppy** [SAGIRI-kawaii/sagiri-bot#123]
**原因**
为什么想要这个功能
看群友聊天想的
**功能简述**
想要个怎样的功能
1.群成员戳机器人时回复一些高二刺猿浓度的语句
2.当群成员@机器人并发送"戳我"是，机器人可随机回应"就不","我戳"以及"我戳，我再戳"等连戳内容（
**功能逻辑**
如何交互、如何使用等
不需要可关闭（
**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的实例等

但是我知道你懒hh

**Comment by nullqwertyuiop** [comment]
但是这个模块写出来可能要限制 mirai 的登录协议？
记得协议是 ANDROID_PHONE 才会相应戳一戳

**Comment by nullqwertyuiop** [comment]
我这里写好了（）
pr过来吗

**Comment by SAGIRI-kawaii** [comment]
> 我这里写好了（） pr过来吗

可（

**Comment by nullqwertyuiop** [comment]
好像第二条和开关都没写，到时候再整（
我这里源码改动太大了没办法直接一次全合并过来了已经（
