### ISSUE TITLE
[Bug Report] 机器人复读时会无视自己发送的消息

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#128]
**环境信息**

系统版本: Debian Buster x64
源码版本: commit bc2cf89a03277fca4a2a74da7414a6f934aa47ff
其他信息: MySQL

**问题描述**
连续两次触发色图功能时，机器人会复读一次触发词，其他功能同理，机器人会无视自己发送的消息进行复读

**日志**

点击文本框下面小长条可以上传文件

**Comment by SAGIRI-kawaii** [comment]
确实会无视（

**Comment by nullqwertyuiop** [comment]
猜猜，因为也没写（）
