### ISSUE TITLE
[Bug Report] long_text_type 设置为 img 时机器人仍以文本形式发送长文本

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#133]
**环境信息**

系统版本: Debian Buster x64
源码版本: -
其他信息: MySQL

**问题描述**
发生了什么情况？有什么现状？是否可复现？
![1cea6bb2c34e09ec.png](https://user-images.githubusercontent.com/49110142/131223477-3cc32105-3187-4a28-af8c-936d8fa4a64e.png)

**日志**
-
点击文本框下面小长条可以上传文件（手机版冇小长条啊）

**Comment by SAGIRI-kawaii** [comment]
因为这个没写，长文本只有部分功能才有

**Comment by SAGIRI-kawaii** [comment]
所以是不是这个也可以关掉（x
