### ISSUE TITLE
[Bug Report]报错 undefined symbol: SKP_Silk_resampler_private_up2_HQ

### ISSUE THREAD

**Issue by meng-luo** [SAGIRI-kawaii/sagiri-bot#135]
**环境信息**

系统版本: Linux orangepipc 5.10.60-sunxi #21.08.1 SMP Wed Aug 25 18:19:32 UTC 2021 armv7l GNU/Linux
源码版本: 2.1.7
其他信息: python3.9  graiax-silkcoder=0.0.16

运行主程序报错：
ImportError: /usr/local/lib/python3.9/site-packages/graiax/silkcoder/_silkv3.cpython-39-arm-linux-gnueabihf.so: undefined symbol: SKP_Silk_resampler_private_up2_HQ
![Snipaste_2021-08-30_14-35-29](https://user-images.githubusercontent.com/79274361/131296165-d4ca2ba7-c713-408c-b2ab-fcc68da4dda6.png)
![Snipaste_2021-08-30_14-39-35](https://user-images.githubusercontent.com/79274361/131296223-05c2deff-8128-4254-b9ed-22fc26c9d71e.png)
![Snipaste_2021-08-30_14-39-54](https://user-images.githubusercontent.com/79274361/131296313-c7025e73-488f-468d-8992-19d5f7918007.png)

**Comment by SAGIRI-kawaii** [comment]
graiax-silkcoder问题，请前往 [graiax-silkcoder](https://github.com/I-love-study/graiax-silkcoder) 处提交ISSUE
