### ISSUE TITLE
[Bug Report] 自动通过加群邀请时不会向主人号码发送通知

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#136]
**环境信息**

系统版本: Debian Buster x64
源码版本: fa29208ea2bcb15d702f582a9af15da00762dcef
其他信息: MySQL

**问题描述**
机器人自动通过加群请求（群人数较少或创建新群时）时不会向主人号码发送加群通知

**日志**
--
点击文本框下面小长条可以上传文件

**Comment by SAGIRI-kawaii** [comment]
群人数较少/新群时只能由好友拉入群，但腾讯并不会发送加群请求，而是直接加入，这么的办法（

**Comment by nullqwertyuiop** [comment]
草 我写了（）
直接监听 bot加群的事件
