### ISSUE TITLE
启动baoc

### ISSUE THREAD

**Issue by Air433up** [SAGIRI-kawaii/sagiri-bot#137]
**环境信息**

系统版本:win server 2008
源码版本:2.1.4
报错如下
![image](https://user-images.githubusercontent.com/60246381/131846638-87a70212-896d-4362-8929-5fe14e2fc6f6.png)

**Comment by nullqwertyuiop** [comment]
看看mirai-api-http的配置的端口是不是8080

**Comment by Air433up** [comment]
> 看看 mirai-api-http 的设备的端口是不是 8080

是8080，但是mirai-api-http是2.2.0版的

**Comment by SAGIRI-kawaii** [comment]
只支持1.x
