### ISSUE TITLE
[Feature Request] 完善私聊功能及支持私聊的 Handler 模板

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#143]
**原因**
为什么想要这个功能
#139

**功能简述**
想要个怎样的功能

**功能逻辑**
如何交互、如何使用等

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的实例等

**Comment by nullqwertyuiop** [comment]
这个也写了但是因为写的太屎不好意思pr所以还是打算蹲个更新.jpg

**Comment by SAGIRI-kawaii** [comment]
妹有模板了，直接像正常saya一样就可以（
