### ISSUE TITLE
[Bug Report] 更改 Bot 的 QQ 号而不使用新数据库时 Bot 不对旧 Bot 号作出回应

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#144]
**环境信息**

系统版本: Debian Buster x64
源码版本: b01d9c79f717e90cf9581723104d7b0b2ad734a3
其他信息: MySQL

**问题描述**
更换机器人账号时机器人账号不对旧有的机器人账号的任何操作进行回应，即便手动在数据库中插入旧有机器人账号的 4 级权限。
控制台及输出日志可见机器人收到消息，但并没有返回处理的结果，包括模块功能调用和设置更变。
除旧有机器人账号外，其他账号均可正常调用所有功能。
MySQL 执行 ``` SELECT * FROM `user_permission` WHERE `member_id` = [旧 Bot QQ]` ``` 返回的查询结果为空。

**日志**
EOF

**Comment by nullqwertyuiop** [comment]
改了，不改 config 怎么跑得起来（）
-------- 原始信息 --------发件人： ZAPHAKIEL ***@***.***> 日期: 2021/10/10  23:21  (GMT+08:00) 收件人： SAGIRI-kawaii/sagiri-bot ***@***.***> 抄送： Nul ***@***.***>, Author ***@***.***> 主题： Re: [SAGIRI-kawaii/sagiri-bot] [Bug Report] 更改 Bot 的 QQ 号而不使用新数据库时 Bot 不对旧 Bot 号作出回应 (#144) 

（config改了吗

**Comment by SAGIRI-kawaii** [comment]
不寄到为啥，但是应该可以偷懒关掉吧（x
