### ISSUE TITLE
重构计划

### ISSUE THREAD

**Issue by SAGIRI-kawaii** [SAGIRI-kawaii/sagiri-bot#15]
## 计划要完成的事项
- 优化代码结构
- 优化内部逻辑
- 支持插件加载
- 使用ORM框架
- 添加一些新功能
- 完整的使用文档
- 更加简洁的管理指令
- 友好的web端管理界面
- 缩减无用功能，精简代码
- 使用sqlite，不用再配置数据库

如果有想要的新功能可以在下方告诉小编哦（不是x
我会考虑考虑🕊（

**Comment by SAGIRI-kawaii** [comment]
## 目前已完成事项
- 支持插件加载
- 使用ORM框架
- 支持插件加载
- 更加简洁的管理指令
- 缩减无用功能，精简代码
- 使用sqlite，不用再配置数据库

**Comment by SAGIRI-kawaii** [comment]
事项已基本完成

**Comment by SAGIRI-kawaii** [comment]
发现结构设计缺陷，即将再次重构，首要目标为提高机器人响应速度

**Comment by FROZENJJ** [comment]
鬼鬼，大工程

**Comment by SAGIRI-kawaii** [comment]
确认为orm问题，正在更改

**Comment by SAGIRI-kawaii** [comment]
重构完成
