### ISSUE TITLE
能不能把web控制台端口映射出去通过ip+端口的形式访问

### ISSUE THREAD

**Issue by FROZENJJ** [SAGIRI-kawaii/sagiri-bot#151]
**原因**
每次调一些权限都需要远程访问服务器有点麻烦，毕竟已经有这个网页端的控制台了希望可以利用起来

**Comment by FROZENJJ** [comment]
内网的服务器，安全性应该不用考虑

**Comment by nullqwertyuiop** [comment]
修改 WebManager/web_manager.py 第 99 行，`host=本机 IP`
替换 WebManager/websocket.py 第 27 行的 `127.0.0.1` 为本机 IP
替换 WebManager/index.html 中所有 `localhost` 为此前填写的 IP
开放 8000 和 8001 端口
（可选）复制 index.html 到网站目录

（不保证一定可用）
