### ISSUE TITLE
[Bug Report][低优先级] 戳一戳触发问题

### ISSUE THREAD

**Issue by ForeverOpp** [SAGIRI-kawaii/sagiri-bot#159]
**环境信息**

系统版本: CentOS 7
源码版本: Latest, 2021.12.03, 23:43
其他信息:

**问题描述**

QQ 会限制戳一戳频率，想要完全触发机器人的回复，三次以上就比较困难了，建议间隔时间随次数增加。

**日志**
无

**Comment by nullqwertyuiop** [comment]
这样吗（）
我这里设置的是 1 分钟重置 暂时没考虑到随次数增加时间
被戳后会重置 1 分钟计时 如果现在需要的话可以改`minutes=分钟数` 我回去再改改这个（）

**Comment by SAGIRI-kawaii** [comment]
> 这样吗（）
> 我这里设置的是 1 分钟重置 暂时没考虑到随次数增加时间
> 被戳后会重置 1 分钟计时 如果现在需要的话可以改`minutes=分钟数` 我回去再改改这个（）

你的mirai和graia版本都是啥啊，我昨天试了一下会报错（

**Comment by nullqwertyuiop** [comment]
> > 这样吗（）
> > 我这里设置的是 1 分钟重置 暂时没考虑到随次数增加时间
> > 被戳后会重置 1 分钟计时 如果现在需要的话可以改`minutes=分钟数` 我回去再改改这个（）
> 
> 你的mirai和graia版本都是啥啊，我昨天试了一下会报错（

忘了 我去瞟一眼（

**Comment by nullqwertyuiop** [comment]
> > 这样吗（）
> > 我这里设置的是 1 分钟重置 暂时没考虑到随次数增加时间
> > 被戳后会重置 1 分钟计时 如果现在需要的话可以改`minutes=分钟数` 我回去再改改这个（）
> 
> 你的mirai和graia版本都是啥啊，我昨天试了一下会报错（

mirai-*                2.7.1-stable
graia-application-mirai 0.19.2
graia-broadcast         0.8.11
graia-saya              0.0.8
graia-scheduler         0.0.4
graiax-silkcoder        0.0.8

**Comment by nullqwertyuiop** [comment]
可能是 broadcast 版本低了？
NudgeEvent好像是新加进去的

**Comment by SAGIRI-kawaii** [comment]
并入 #212
