### ISSUE TITLE
[Bug Report] 坦白说功能事件解析错误

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#160]
**环境信息**

系统版本: Debian Buster x64
源码版本: 2c5ab47e2f9e4ccf6cc64bd5be298846d79f4eab
其他信息: 
MySQL 5.7
mirai-* 2.7.1-stable
graia-application-mirai 0.19.2
graia-broadcast 0.8.11
graia-saya 0.0.8
graia-scheduler 0.0.4
graiax-silkcoder 0.0.8

**问题描述**
如图
![4dc271207ec62a9.jpg](https://user-images.githubusercontent.com/49110142/144780943-d735d82f-5a12-4907-8719-80386108b4cb.jpg)
```
@bcc.receiver("GroupAllowConfessTalkEvent")
async def group_allow_confess_talk_changed(app: GraiaMiraiApplication, event: GroupAllowConfessTalkEvent):
    try:
        await app.sendGroupMessage(
            event.group, MessageChain.create([
                Plain(text=f"坦白说功能已{'开启。' if event.current else '关闭。'}")
            ])
        )
    except AccountMuted:
        pass
```
按照第 6 行的看好像效果反了？不清楚是不是只有我这里是这样。

**日志**

**Comment by SAGIRI-kawaii** [comment]
我好像没问题（
