### ISSUE TITLE
[Bug Report] 使用长文本生成图片时图片长度过短

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#166]
**环境信息**

系统版本: Debian Buster x64
源码版本: de50277c340db83fdb2ed902c1861df060ab070e
其他信息: 

**问题描述**
使用较长文本调用 SAGIRIBOT.utils.MessageChainUtils.messagechain_to_img() 时生成的图片长度过短，使部分文本被裁去

**日志**
原文
```
历史上的今天
----------
2020年：被中华民国国家通讯传播委员会裁定不获换照的中天新闻台正式停播，结束26年的电视广播历史。
2015年：联合国气候变化框架公约下的《巴黎协定》正式生效。
2012年：北朝鲜成功发射光明星3号卫星。
2010年：由包括复旦大学学生在内的18人组成的登山队在黄山迷路，黄山民警张宁海在搜救时殉职，而登山队员获救后态度冷漠，是为复旦黄山门事件或复旦十八驴事件。
2010年：中国首个极深地下实验室中国锦屏地下实验室投入使用。
2009年：香港奥运足球代表队于2009年东亚运动会足球比赛决赛于互射十二码阶段击败日本国家足球队，历史性首次赢得国际性综合体育项目冠军。
2006年：日本线上影片分享网站《NICONICO动画（暂定版）》开放测试浏览。
2004年：索尼电脑娱乐的最新家用便携式游戏机PlayStation Portable问世。
1994年：上海地铁一号线开通。
1989年：香港政府首次执行当然遣返，将51名非自愿返回越南的船民送返。
1985年：美国101空降师士兵搭乘的艾罗航空1285号班机在加拿大纽芬兰岛起飞时坠毁，造成248人死亡。
1984年：美国天文学家观测到太阳系外第一颗行星。
1979年：韩国陆军少将全斗焕发动军事政变，逮捕与其不和的陆军参谋总长郑昇和，实质掌握韩国军政权力。
1973年：文化大革命：《北京日报》发表了《一个小学生的来信和日记摘抄》，并加长篇编者按语，掀起“破师道尊严”浪潮，是为黄帅事件。
1963年：肯尼亚脱离英国统治，宣布独立，乔莫·肯雅塔就任第一任总统。
1949年：中华人民共和国根据《开罗宣言》和《波茨坦公告》宣布对南沙群岛的主权。
1946年：中华民国派兵进驻西沙和南沙群岛。
1942年：第二次世界大战：纳粹德国军队发起冬季风暴作战，尝试救出在斯大林格勒战役中遭包围的轴心国军队。
1941年：第二次世界大战 ：珍珠港事件：匈牙利王国、罗马尼亚王国、保加利亚王国和斯洛伐克第一共和国对美国宣战。
1936年：国民革命军将领张学良、杨虎城于西安挟持国民政府军事委员会委员长蒋中正，要求其停止剿匪，立即抗日。
1925年：伊朗巴列维王朝建立。
1915年：中华民国大总统袁世凯宣布更改国号而将隔年订为洪宪元年，准备就任中华帝国皇帝。
1911年：德里取代加尔各答成为印度的首都。
1901年：意大利发明家古列尔莫·马可尼的研究小组，在加拿大接收到从英国发送出来的第一个横跨大西洋的无线电信号。
1897年：巴西第一个经规划建设的城市美景市落成，取代欧鲁普雷图成为米纳斯吉拉斯州首府。
1887年：土耳其向西方国家呼吁，要求调解同俄国的战争。
1804年：拿破仑战争：西班牙对英国宣战。
1787年：宾夕法尼亚州批准美国宪法，是第二个批准美国宪法的州。
1642年：荷兰航海家亚伯·塔斯曼发现新西兰。
1574年：奥斯曼帝国穆拉德三世在塞利姆二世死后继位为苏丹。
884年：西法兰克王国国王卡洛曼二世去世，查理三世即位，法兰克王国短暂统一。
617年：李渊的军队攻破隋朝的都城大兴城。
```
生成图片
![7DUI}TC67P6FJ}EU1S{SAAY](https://user-images.githubusercontent.com/49110142/145705020-99c6ea22-c3bf-4075-a7c5-0042a643e9c7.png)

**Comment by sxjeru** [comment]
`LeetCode每日一题`有相同问题。

[举例.png](https://user-images.githubusercontent.com/20513115/146128247-e2a9a4ca-118d-4569-9a9e-957d78820863.png)

**Comment by SAGIRI-kawaii** [comment]
有没有例子，我看今天每日一题是正常的（

**Comment by nullqwertyuiop** [comment]
直接发送这个可以重现```
/merge 历史上的今天
----------
2002年：王冠闳，台湾男子游泳运动员
1999年：永濑廉，日本杰尼斯事务所男子偶像团体King & Prince成员
1998年：Yuto，韩国男子偶像团体PENTAGON成员
1998年：XXXTentacion， 美国男性饶舌歌手（2018年逝世）
1995年：肖宇梁，中国男演员
1995年：Wyatt，韩国男子偶像团体ONF成员
1995年：李瑜瑛，韩国女子偶像团体Hello Venus成员
1995年：王霜，中国足球员
1994年：利路修，俄罗斯籍爆红明星
1993年：松永真穗，日本女性声优
----------
第 1 页，共 5 页
发送 "历史上的今天 页数" 翻页
发送 "历史上的今天 0" 查看所有内容历史上的今天
----------
1992年：特林德尔·玲奈，日本模特儿、艺人
1989年：黄心颖，香港女艺人
1989年：曾雅妮，台湾女子高尔夫球选手
1985年：San E，韩国饶舌歌手
1985年：杜鲁筝·克鲁斯，荷兰超模
1984年：阿扬·罗本，荷兰足球员
1982年：韦宗成，台湾漫画家
1981年：王友良，香港歌手
1981年：龚睿那，中国羽毛球运动员
1981年：张景淳，香港演员
----------
第 2 页，共 5 页
发送 "历史上的今天 页数" 翻页
发送 "历史上的今天 0" 查看所有内容历史上的今天
----------
1980年：夏目奈奈，日本AV女优
1980年：黄雨欣，台湾演员
1976年：室刚，日本男演员
1976年：李心洁，马来西亚女歌手
1974年：漆原友纪，日本漫画家
1973年：S·克雷格·札勒，美国小说家、编剧、导演、摄影指导、音乐家
1972年：杨峥，香港模特儿
1969年：安德烈·坎切尔斯基，俄罗斯足球运动员
1968年：高户靖广，日本声优
1967年：玛格达莱娜·安德松，瑞典政治家
----------
第 3 页，共 5 页
发送 "历史上的今天 页数" 翻页
发送 "历史上的今天 0" 查看所有内容历史上的今天
----------
1962年：理查·罗森堡，澳洲男演员
1961年：殷正洋，台湾歌手
1958年：恬妞，台湾女演员
1957年：卡罗琳，摩纳哥公主，汉诺威王妃
1954年：小日向文世，日本演员
1950年：李察·狄恩·安德森，美国电视演员
1938年：巨人马场，日本职业摔角手（1999年逝世）
1935年：罗德丞，香港政治人物（2006年逝世）
1930年：德里克·沃尔科特，圣卢西亚诗人（2017年逝世）
1907年：汤川秀树，日本物理学者（1981年逝世）
----------
第 4 页，共 5 页
发送 "历史上的今天 页数" 翻页
发送 "历史上的今天 0" 查看所有内容历史上的今天
----------
1897年：苏巴斯·钱德拉·鲍斯，印度律师和政治人物（1945年逝世）
1893年：谢尔盖·爱森斯坦，苏联电影导演（1948年逝世）
1872年：朗之万，法国物理学家（1946年逝世）
1862年：大卫·希尔伯特，德国数学家（1943年逝世）
1832年：爱德华·马奈，法国画家（1883年逝世）
1828年：西乡隆盛，日本政治家（1877年逝世）
1783年：司汤达，法国作家（1842年逝世）
1340年：元昭宗爱猷识理答腊，北元皇帝（1378年逝世）
599年：唐太宗李世民，唐朝皇帝（649年逝世）
----------
第 5 页，共 5 页
发送 "历史上的今天 页数" 翻页
发送 "历史上的今天 0" 查看所有内容
```

**Comment by nullqwertyuiop** [comment]
草 ----------被当成分割线了

**Comment by SAGIRI-kawaii** [comment]
![test](https://user-images.githubusercontent.com/45849471/150680719-3ad2e6d6-ffa4-4112-b32c-02f39f8b1871.png)
这不是正常的（

**Comment by nullqwertyuiop** [comment]
怪欸 我这里被切了一部分

**Comment by nullqwertyuiop** [comment]
![QQ图片20220123212857](https://user-images.githubusercontent.com/49110142/150680798-0ad910b4-2ce2-45bc-9131-ac8716388ea7.png)

**Comment by SAGIRI-kawaii** [comment]
怪（

**Comment by nullqwertyuiop** [comment]
我以为是符号多了所以被切，然后刚刚用符号测也只是切了最后一行
```
/merge 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_
```

**Comment by SAGIRI-kawaii** [comment]
> 我以为是符号多了所以被切，然后刚刚用符号测也只是切了最后一行
> 
> ```
> /merge 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_ 64-@ 65-A 66-B 67-C 68-D 69-E 70-F 71-G 72-H 73-I 74-J 75-K 76-L 77-M 78-N 79-O 80-P 81-Q 82-R 83-S 84-T 85-U 86-V 87-W 88-X 89-Y 90-Z 91-[ 92-\\ 93-] 94-^ 95-_
> ```

这个我也没有问题（

**Comment by nullqwertyuiop** [comment]
怪诶
![e503f349b40e558.png](https://user-images.githubusercontent.com/49110142/150681290-451acf1f-b89e-4eae-a9ce-419a5a6e7f9c.png)
而且每次都是只切最后一行

草又是这个tag（）

**Comment by SAGIRI-kawaii** [comment]
使用 `TextEngine` 后应该不会出现过短问题
