### ISSUE TITLE
[Bug Report] MiraiEventHandler.py 模块是否存在问题？

### ISSUE THREAD

**Issue by sxjeru** [SAGIRI-kawaii/sagiri-bot#168]
**环境信息**

系统版本: Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-90-generic x86_64)
源码版本: v2.1.7
其他信息: mirai-api-http-v1.12.0

**问题描述**

~~感觉 MiraiEventHandler.py 里面的事件触发有些迷，有些貌似不会触发，希望能给出触发条件。~~
此外能否可选禁用该模块？（感觉有点尬……）

**Comment by nullqwertyuiop** [comment]
#104

**Comment by nullqwertyuiop** [comment]
部分事件不清楚是 mirai 版本不支持还是 graia-application 的问题不会触发，但是在以前的版本可用，推测是 tx 作妖。

**Comment by nullqwertyuiop** [comment]
等适配新版本的 mirai 吧

**Comment by nullqwertyuiop** [comment]
不需要的话直接删掉这个 Handler 就行了（
