### ISSUE TITLE
[Bug Report] [高优先级] 这咋还把 B 站小程序识别更坏了啊

### ISSUE THREAD

**Issue by ForeverOpp** [SAGIRI-kawaii/sagiri-bot#172]
**环境信息**

系统版本: CentOS 7
源码版本: Latest, 2021/12/16
其他信息: 别的啥都没动

**问题描述**
看到群里新增了说『是』就回复一段话的功能，遂用`git pull`更新了一下源码，然后发现哔哩哔哩小程序转链接失败。
另问一下这个关键字触发咋设置，每次回复的话都不一样，感觉可能是加了什么新 API。

**日志**
Sagiri 日志
```log
2021-12-17 00:42:14.122 | INFO     | __main__:group_message_handler:49 - 收到来自群 <********> 中成员 <***> 的消息：[APP消息]
Traceback (most recent call last):
  File "/root/anaconda3/envs/QQBot/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "/root/anaconda3/envs/QQBot/lib/python3.8/site-packages/graia/broadcast/utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "/root/QQBot/sagiri-bot/SAGIRIBOT/Handler/Handlers/BilibiliAppParserHandler.py", line 26, in bilibili_app_parser_handler
    if result := await BilibiliAppParserHandler.handle(app, message, group, member):
  File "/root/QQBot/sagiri-bot/SAGIRIBOT/decorators.py", line 92, in wrapper
    return await func(*args, **kwargs)
  File "/root/QQBot/sagiri-bot/SAGIRIBOT/decorators.py", line 116, in wrapper
    return await func(*args, **kwargs)
  File "/root/QQBot/sagiri-bot/SAGIRIBOT/Handler/Handlers/BilibiliAppParserHandler.py", line 56, in handle
    return MessageItem(await BilibiliAppParserHandler.generate_messagechain(result), Normal(GroupStrategy()))
  File "/root/QQBot/sagiri-bot/SAGIRIBOT/Handler/Handlers/BilibiliAppParserHandler.py", line 105, in generate_messagechain
    chain_list.append(Plain(text=f"\n【分区】{bilibili_partition_dict[str(data['tid'])]['name']}->{data['tname']}\n"))
KeyError: '232'
```
Mirai 日志
```json
[mirai: app: {
    "app": "com.tencent.miniapp_01",
    "config": {
        "autoSize": 0,
        "ctime": 1639672933,
        "forward": 1,
        "height": 0,
        "token": "7e0754419e************f17",
        "type": "normal",
        "width": 0
    },
    "desc": "哔哩哔哩",
    "extra": {
        "app_type": 1,
        "appid": 100951776,
        "uin": 28 ** ** 802
    },
    "meta": {
        "detail_1": {
            "appid": "1109937557",
            "desc": "【熟肉|绝不是炒冷饭】太空导航（如何在太空不迷路|巨长，特无聊，慎看）1968【NASA|USAF】",
            "gamePoints": "",
            "gamePointsUrl": "",
            "host": {
                "nick": "空白",
                "uin": 2805027802
            },
            "icon": "https://open.gtimg.cn/open/app_icon/00/95/17/76/100951776_100_m.png?t=1639568686",
            "preview": "pubminishare-30161.picsz.qpic.cn/e32f5da3-c471-4a17-b28a-b28ac0ffa00e",
            "qqdocurl": "https://b23.tv/y4YPgrj?share_medium=android&share_source=qq&bbid=XZC8****F96223393&ts=1639672926121",
            "scene": 1036,
            "shareTemplateData": {},
            "shareTemplateId": "8C8E89B49B****DBABA4",
            "showLittleTail": "",
            "title": "哔哩哔哩",
            "url": "m.q.qq.com/a/s/133370e823bb1e1881f92b9328dffbbd"
        }
    },
    "needShareCallBack": false,
    "prompt": "[QQ小程序]哔哩哔哩",
    "ver": "1.0.0.19",
    "view": "view_8C8E89B4*******BABA4"
}]
```

**Comment by nullqwertyuiop** [comment]
对不起，但是我没看懂（）
请问源代码的 commit 是？

**Comment by nullqwertyuiop** [comment]
至于 KeyError 问题，有可能是 B 站设置了新分区而 Bot 的静态文件尚未更新，可尝试使用 `try`。

**Comment by ForeverOpp** [comment]
> 对不起，但是我没看懂（） 请问源代码的 commit 是？

我的源码落后了几个版本，上次正常是在 Commit 2c5ab47e2f9e4ccf6cc64bd5be298846d79f4eab 。

**Comment by nullqwertyuiop** [comment]
了解，请问本次出现问题的 commit 是？

**Comment by ForeverOpp** [comment]
> 了解，请问本次出现问题的 commit 是？

从 b9a47050417a36e6f5d2b80a2ece7309c08d8707 之后的版本其中之一，也可能与版本更新无关，我看后续 Commit 没有涉及到哔哩哔哩 Handler 的更新。出问题的源码版本是最新的。

**Comment by nullqwertyuiop** [comment]
好的，请稍等，正在就您的第二项问题编辑回复。

**Comment by ForeverOpp** [comment]
> 至于 KeyError 问题，有可能是 B 站设置了新分区而 Bot 的静态文件尚未更新，可尝试使用 `try`。

有可能，建议一段时间从 B 站主页获取一下所有分区列表。

**Comment by nullqwertyuiop** [comment]
支持关键词触发的功能：
* 二次元（等）图片
* 自定义回复

二次元（等）图片设置关键词方法：
在群组内发送 `添加功能关键词#类型#关键词` 设置发送图片的关键词
如 `添加功能关键词#setu#发张色图`
发送 `删除功能关键词#关键词` 可删除触发发送图片的关键词

自定义回复设置关键词方法：
在群组内发送 `添加回复关键词#触发文本#回复内容` 设置自定义回复
**回复内容仅可为图片或文本**
设置后可发送设定的 `触发文本` 取得自定义的回复，该回复不与设置的 `speak_mode` 冲突
发送 `删除回复关键词#触发文本` 可删除触发自定义回复的关键词

以上提及的关键词设置后**全局**有效

**Comment by nullqwertyuiop** [comment]
> > 至于 KeyError 问题，有可能是 B 站设置了新分区而 Bot 的静态文件尚未更新，可尝试使用 `try`。
> 
> 有可能，建议一段时间从 B 站主页获取一下所有分区列表。

暂时对这方面了解的不够多，我试试写一个临时的解决方案

**Comment by ForeverOpp** [comment]
> 支持关键词触发的功能：
> 
> * 二次元（等）图片
> * 自定义回复
> 
> 二次元（等）图片设置关键词方法： 在群组内发送 `添加功能关键词#类型#关键词` 设置发送图片的关键词 如 `添加功能关键词#setu#发张色图` 发送 `删除功能关键词#关键词` 可删除触发发送图片的关键词
> 
> 自定义回复设置关键词方法： 在群组内发送 `添加回复关键词#触发文本#回复内容` 设置自定义回复 **回复内容仅可为图片或文本** 设置后可发送设定的 `触发文本` 取得自定义的回复，该回复不与设置的 `speak_mode` 冲突 发送 `删除回复关键词#触发文本` 可删除触发自定义回复的关键词
> 
> 以上提及的关键词设置后**全局**有效

好家伙，也就是说那么多回复都是手动设置的啊，那太麻烦了吧。而且我感觉 Owner 也没在群组里进行设置啊，我给您截个图：
![image](https://user-images.githubusercontent.com/9302540/146416797-dcee383b-15d3-4f2c-b951-ada64590b79d.png)

**Comment by nullqwertyuiop** [comment]
是的，只需在某个群组中设置自定义回复即可，设置后全局有效，即在其他群组中仍可通过该关键词获取自定义回复

**Comment by nullqwertyuiop** [comment]
> > > 至于 KeyError 问题，有可能是 B 站设置了新分区而 Bot 的静态文件尚未更新，可尝试使用 `try`。
> > 
> > 
> > 有可能，建议一段时间从 B 站主页获取一下所有分区列表。
> 
> 暂时对这方面了解的不够多，我试试写一个临时的解决方案

临时的解决方案见 #173

**Comment by ForeverOpp** [comment]
> > > > 至于 KeyError 问题，有可能是 B 站设置了新分区而 Bot 的静态文件尚未更新，可尝试使用 `try`。
> > > 
> > > 
> > > 有可能，建议一段时间从 B 站主页获取一下所有分区列表。
> > 
> > 
> > 暂时对这方面了解的不够多，我试试写一个临时的解决方案
> 
> 临时的解决方案见 #173

看了一下代码，确实是静态文件没有分区编号的问题，但是我觉得这分区没必要静态存啊，API 本身会返回分区的中文标签，类似这样：
```json
{"tid":232,"tname":"工业·工程·机械"}
```
在`tname`字段，完全可以先尝试用`tname`，不行再在本地查询。

**Comment by ForeverOpp** [comment]
> > > > > 至于 KeyError 问题，有可能是 B 站设置了新分区而 Bot 的静态文件尚未更新，可尝试使用 `try`。
> > > > 
> > > > 
> > > > 有可能，建议一段时间从 B 站主页获取一下所有分区列表。
> > > 
> > > 
> > > 暂时对这方面了解的不够多，我试试写一个临时的解决方案
> > 
> > 
> > 临时的解决方案见 #173
> 
> 看了一下代码，确实是静态文件没有分区编号的问题，但是我觉得这分区没必要静态存啊，API 本身会返回分区的中文标签，类似这样：
> 
> ```json
> {"tid":232,"tname":"工业·工程·机械"}
> ```
> 
> 在`tname`字段，完全可以先尝试用`tname`，不行再在本地查询。

啊看到 Pull Request 了，就是先查本地再用 API 返回的，也可以。
辛苦了。

**Comment by nullqwertyuiop** [comment]
不辛苦，若有后续报错请告知我，谢谢

**Comment by ForeverOpp** [comment]
> 是的，只需在某个群组中设置自定义回复即可，设置后全局有效，即在其他群组中仍可通过该关键词获取自定义回复

哦，我之前看就觉得只有这个功能可以实现，还以为是什么新功能哈哈。

**Comment by SAGIRI-kawaii** [comment]
超，竟然有群友

**Comment by nullqwertyuiop** [comment]
超，怎么你们都认识

**Comment by ForeverOpp** [comment]
> 超，竟然有群友

老群友了哈哈哈，感觉用这个机器人的都是群友（

**Comment by nullqwertyuiop** [comment]
> > 超，竟然有群友
> 
> 老群友了哈哈哈，感觉用这个机器人的都是群友（

我不是（）
我从 mamoe/mirai 仓库来的

**Comment by ForeverOpp** [comment]
> > > 超，竟然有群友
> > 
> > 
> > 老群友了哈哈哈，感觉用这个机器人的都是群友（
> 
> 我不是（） 我从 mamoe/mirai 仓库来的

😂 Mirai 那里确实推荐了不少人过来

**Comment by nullqwertyuiop** [comment]
> > > > 超，竟然有群友
> > > 
> > > 
> > > 老群友了哈哈哈，感觉用这个机器人的都是群友（
> > 
> > 我不是（） 我从 mamoe/mirai 仓库来的
> 
> 😂 Mirai 那里确实推荐了不少人过来

很好用，孩子很喜欢，累计用户已经 3k 了，还会继续用下去
