### ISSUE TITLE
[Feature Request] Ariadne 适配

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#174]
**原因**
[Ariadne](https://github.com/GraiaProject/Ariadne) 已支持 `mirai-api-http >= 2.0`
[`Ariadne` -> `Graia-Application`变动的 API](https://graia.readthedocs.io/porting/cheatsheet/)

**功能简述**
支持 `Ariadne`

**功能逻辑**

**实现参考**

**Comment by ForeverOpp** [comment]
快支持吧，已经发不出去图了

**Comment by nullqwertyuiop** [comment]
我写了哦（）

**Comment by nullqwertyuiop** [comment]
但是暂时还没 push 上来，还在测试有没有 bug
目前看应该没有

**Comment by nullqwertyuiop** [comment]
稍等 今年应该可以 push 好

**Comment by nullqwertyuiop** [comment]
@ForeverOpp 已 push 至 [nullqwertyuiop/sagiri-bot:patch-4](https://github.com/nullqwertyuiop/sagiri-bot/tree/patch-4)
**使用前请阅读 #176**
**如写有模块则需按照 [Ariadne 官方文档](https://graiaproject.github.io/Ariadne/index.html) 修改**

**Comment by ForeverOpp** [comment]
> 

还得切分支（
话说Owner忙完了吧，快叫他来Merge

**Comment by nullqwertyuiop** [comment]
> > @ForeverOpp 已 push 至 [nullqwertyuiop/sagiri-bot:patch-4](https://github.com/nullqwertyuiop/sagiri-bot/tree/patch-4) **使用前请阅读 #176** **如写有模块则需按照 [Ariadne 官方文档](https://graiaproject.github.io/Ariadne/index.html) 修改**
> 
> 还得切分支（ 话说Owner忙完了吧，快叫他来Merge

不知道，至少我这里不建议直接 merge
有两个模块需要复查

**Comment by ForeverOpp** [comment]
> > > @ForeverOpp 已 push 至 [nullqwertyuiop/sagiri-bot:patch-4](https://github.com/nullqwertyuiop/sagiri-bot/tree/patch-4) **使用前请阅读 #176** **如写有模块则需按照 [Ariadne 官方文档](https://graiaproject.github.io/Ariadne/index.html) 修改**
> > 
> > 
> > 还得切分支（ 话说Owner忙完了吧，快叫他来Merge
> 
> 不知道，至少我这里不建议直接 merge 有两个模块需要复查

这两个模块其实暂时没啥用（

**Comment by nullqwertyuiop** [comment]
> > > > @ForeverOpp 已 push 至 [nullqwertyuiop/sagiri-bot:patch-4](https://github.com/nullqwertyuiop/sagiri-bot/tree/patch-4) **使用前请阅读 #176** **如写有模块则需按照 [Ariadne 官方文档](https://graiaproject.github.io/Ariadne/index.html) 修改**
> > > 
> > > 
> > > 还得切分支（ 话说Owner忙完了吧，快叫他来Merge
> > 
> > 
> > 不知道，至少我这里不建议直接 merge 有两个模块需要复查
> 
> 这两个模块其实暂时没啥用（

要不，直接 clone 我的仓库分支好了，或者其他几个支持 Ariadne 的机器人

**Comment by ForeverOpp** [comment]
> > > > > @ForeverOpp 已 push 至 [nullqwertyuiop/sagiri-bot:patch-4](https://github.com/nullqwertyuiop/sagiri-bot/tree/patch-4) **使用前请阅读 #176** **如写有模块则需按照 [Ariadne 官方文档](https://graiaproject.github.io/Ariadne/index.html) 修改**
> > > > 
> > > > 
> > > > 还得切分支（ 话说Owner忙完了吧，快叫他来Merge
> > > 
> > > 
> > > 不知道，至少我这里不建议直接 merge 有两个模块需要复查
> > 
> > 
> > 这两个模块其实暂时没啥用（
> 
> 要不，直接 clone 我的仓库分支好了，或者其他几个支持 Ariadne 的机器人

我太懒了（（（（（
只想`git pull`，多一条命令都不想打

~~被机器人部署折磨后的后遗症~~

**Comment by nullqwertyuiop** [comment]
实惨

**Comment by SAGIRI-kawaii** [comment]
在写了在写了（x

**Comment by ForeverOpp** [comment]
> 在写了在写了（x

好！很有精神！（

**Comment by nullqwertyuiop** [comment]
加油 坐等

**Comment by SAGIRI-kawaii** [comment]
已完成大部分迁移
