### ISSUE TITLE
可能打错的部分文本

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#179]
https://github.com/SAGIRI-kawaii/sagiri-bot/blob/95758e0233c2710a954b3fef88ac26ffbf4ab731/sagiri_bot/handler/handler.py#L19
https://github.com/SAGIRI-kawaii/sagiri-bot/blob/95758e0233c2710a954b3fef88ac26ffbf4ab731/sagiri_bot/handler/handlers/fake_forward.py#L26

**Comment by SAGIRI-kawaii** [comment]
哪里错了（x
直接pr.jpg
