### ISSUE TITLE
[Bug Report] MySQL 连接池过小导致抛出错误

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#184]
**环境信息**

系统版本: `Debian Buster x64`
源码版本: `1281aa292a2a90e19643e45000223c60e3a0a25a`
其他信息: `MySQL 5.7`

**问题描述**
机器人短时间内收到过多消息时可能由于 MySQL 连接池过小导致抛出错误。
将 `sagiri_bot.orm.async_orm` 第 35 行起更改为如下内容时可解决该问题（数据库采用 `SQLite` 时进行上述更改将在启动时抛出错误。）。
```
self.engine = create_async_engine(
    db_link,
    echo=False,
    pool_size=40,
    max_overflow=60
)
```

**日志**
~~过于久远~~

**Comment by SAGIRI-kawaii** [comment]
我可以尝试改一下，还有别的什么mysql特有的参数吗，比如字符集之类的

**Comment by nullqwertyuiop** [comment]
字符集 `utf8mb4`

**Comment by nullqwertyuiop** [comment]
以及记得 `close()` 连接（
不然 err 日志体积和 `Aborted clients` 数会飞速增长

**Comment by SAGIRI-kawaii** [comment]
已更新，测试下？（我懒得搞mysql环境

**Comment by nullqwertyuiop** [comment]
报错
```
TypeError: Invalid argument(s) 'charset' sent to create_engine(), using configuration MySQLDialect_aiomysql/AsyncAdaptedQueuePool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
```

`pool_size` `max_overflow` 可能写在配置文件里面更好一点，方便修改（？
~~跨年的时候 `pool_size=240, max_overflow=260` 照样挂了（~~

**Comment by SAGIRI-kawaii** [comment]
查了下，charset好像是在链接里自带？类似 'mysql://user:password@1.1.1.1/db?charset=utf8mb4' 这样

**Comment by nullqwertyuiop** [comment]
是的

**Comment by SAGIRI-kawaii** [comment]
现在呢（

**Comment by SAGIRI-kawaii** [comment]
可以在config里自定义参数了
