### ISSUE TITLE
[Bug Report] Bot 不响应任何 Event

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#191]
https://github.com/SAGIRI-kawaii/sagiri-bot/blob/3e6788a3f5dd022565fb15c114ccafc2cc9805f7/sagiri_bot/handler/required_module/mirai_event/__init__.py#L24-L33

运行至此时所有 Event 均 `return None`
此时的变量为
```
event.__class__.__name__ = 'MemberPermissionChangeEvent'
key = 'member_permission_change_event'
func = <function member_permission_change_event at 0x00000272A46169D0>
argument_signatures = [('app', <class 'graia.ariadne.app.Ariadne'>, None), ('group', <class 'graia.ariadne.model.Group'>, None), ('event', <class 'graia.ariadne.event.mirai.MemberPermissionChangeEvent'>, None)]
arg = 'app'
args[arg] = <graia.ariadne.app.Ariadne object at 0x000002729EE2D100>
argument_signatures[1].__class__ = <class 'tuple'>
```

发送其他 Event 时同样无法正常响应

**Comment by SAGIRI-kawaii** [comment]
是最新版嘛（

**Comment by SAGIRI-kawaii** [comment]
之前有bug，修复的刚推上去没多久

**Comment by nullqwertyuiop** [comment]
是的（

**Comment by nullqwertyuiop** [comment]
什 我pull看看

**Comment by nullqwertyuiop** [comment]
怪欸 我这里 `sagiri-bot.sagiri_bot.handler.required_module.mirai_event` 最新一次 commit 还是 3ed4c07fafcb56a79115c97f535b6eb2b3d7f1d3

**Comment by SAGIRI-kawaii** [comment]
graia-ariadne也有bug，在等待修复中 [https://github.com/GraiaProject/Ariadne/issues/83](https://github.com/GraiaProject/Ariadne/issues/83)

**Comment by SAGIRI-kawaii** [comment]
缘赖氏没push上去（x

**Comment by nullqwertyuiop** [comment]
草 没事了

**Comment by SAGIRI-kawaii** [comment]
Ariadne问题已修复，更新 `graia-ariadne==0.5.1rc4`
