### ISSUE TITLE
[Bug Report] required_modules 下的插件可被 SayaManager 卸载

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#192]
**环境信息**

系统版本:
源码版本:
其他信息:

**问题描述**
发送 `卸载插件 ChatRecorder`

**日志**

点击文本框下面小长条可以上传文件

**Comment by nullqwertyuiop** [comment]
我卸我自己.jpg
![1642777767793 png](https://user-images.githubusercontent.com/49110142/150550687-11bff6e0-ff95-41e9-b3f6-55d5b2cc8344.png)

**Comment by SAGIRI-kawaii** [comment]
得想想怎么搞（

**Comment by SAGIRI-kawaii** [comment]
更新插件结构后有望解决

**Comment by nullqwertyuiop** [comment]
在 `metadata` 里面写个 `uninstallable: bool`？

然后 `saya_manager` 卸载前先检查这项是否为 `True`

**Comment by SAGIRI-kawaii** [comment]
确实
