### ISSUE TITLE
[Feature Request] 启动时缓存 `setting` 至内存

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#205]
**原因**
避免拥有读取设置的功能在接收大量信息时占用不必要的连接数，如 `get_setting()` 和 `@switch()`

**功能简述**
启动时将各个群组的设置读取至内存，后期读取时直接调取所缓存的数据。
设置项发生变更时写入数据库并同时更新内存中的缓存数据。

**功能逻辑**
如何交互、如何使用等

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的实例等

**Comment by SAGIRI-kawaii** [comment]
完成
