### ISSUE TITLE
[Bug Report]bizhi图库权限管控无效

### ISSUE THREAD

**Issue by mangokuma** [SAGIRI-kawaii/sagiri-bot#208]
**环境信息**

系统版本:windows10
源码版本:915cbeb
其他信息:

**问题描述**
发生了什么情况？有什么现状？是否可复现？
![IMG_20220217_110447](https://user-images.githubusercontent.com/47619527/154397220-a6c4d219-f076-416e-80cf-b29b9b363217.jpg)

**日志**

点击文本框下面小长条可以上传文件

**Comment by SAGIRI-kawaii** [comment]
更改 `config.yaml` 中 `wallpaper` 项为 `bizhi` 即可
