### ISSUE TITLE
[Bug Report] 图库关键词无法查询

### ISSUE THREAD

**Issue by sxjeru** [SAGIRI-kawaii/sagiri-bot#214]
**环境信息**

系统版本: Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-90-generic x86_64)
源码版本: v3.0.3

**问题描述**

![image](https://user-images.githubusercontent.com/20513115/155953894-dc451689-27ad-4e94-8854-826f7abd24f9.png)
![image](https://user-images.githubusercontent.com/20513115/155953924-3a5da391-aa11-46b7-a45a-0296333f25bb.png)
![image](https://user-images.githubusercontent.com/20513115/155953946-1e599750-3bff-43b3-b92c-4003dd08f16f.png)

**Comment by SAGIRI-kawaii** [comment]
fixed
