### ISSUE TITLE
[Bug Report] 数据表过大时影响启动

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#219]
**问题**
对于 `ChatRecord` 等拥有大量数据的表，启动时 `async_orm` 会尝试获取所有表数据检查表是否存在，造成过多 RAM 占用并影响启动速度

**如何复现**

**预期行为**

**使用环境:**

**日志/截图**

**Comment by SAGIRI-kawaii** [comment]
fixed
