### ISSUE TITLE
文档意见收集

### ISSUE THREAD

**Issue by SAGIRI-kawaii** [SAGIRI-kawaii/sagiri-bot#228]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by nullqwertyuiop** [comment]
#213

**Comment by hcxx** [comment]
1. {} 大括号、[]中括号代表填入关键字，括号外面得一些符号如#是需要填入的
2. emoji融合：功能增加说明：只适用系统表情（如输入法自带经典表情）
3. 关键词回复 ：功能增加示例：添加模糊回复关键词#你好#你好（任意例子即可）

**Comment by blanketbathe** [comment]
小白最纠结的其实是数据库的搭建

**Comment by SAGIRI-kawaii** [comment]
> 

可是使用sqlite根本不需要搭建

**Comment by blanketbathe** [comment]
这就更加说明我是小白了hhh
