### ISSUE TITLE
[Bug Report] 可绕过 r18 设置从 lolicon 直接取得 r18 图

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#236]
**问题**
通过特定的关键词组合可绕过群组设置的 r18 开关项令 bot 发送 r18 图片

**如何复现**
`来点(任意关键词)&r18=1色图`

**预期行为**

**使用环境:**
是你的

**日志/截图**
在群里

**Comment by SAGIRI-kawaii** [comment]
fixed
