### ISSUE TITLE
[Bug Report]无法正常启动

### ISSUE THREAD

**Issue by WindraiteLesd** [SAGIRI-kawaii/sagiri-bot#239]
**问题**
无法正常启动.

**如何复现**
`python main.py`后报错.

**预期行为**
正常启动.

**使用环境:**
- 系统: Windows Server 2019 Datacenter
- MAH 版本:2.5.0
- Ariadne 版本:0.6.10
- Python 版本:3.9.7
- 源码版本:3.1.2
- 其他 Graia 库版本:graia-scheduler==0.0.6, graia-saya==0.0.15, graiax-silkcoder==0.2.0
- 其他 有关 库版本:sagiri-bot 3.1.2所有对应的requirements

**日志/截图**
```
C:\Users\Administrator\Desktop\bot\plugins\sagiri-bot-3.1.2>python main.py
2022-04-29 20:46:23.520 | INFO     | sagiri_bot.core.app_core:__init__:61 - Initializing
2022-04-29 20:46:23.582 | INFO     | sagiri_bot.core.app_core:__init__:85 - Initialize end
2022-04-29 20:46:23.582 | ERROR    | graia.ariadne.util:loguru_excepthook:52 - Exception:
Traceback (most recent call last):

> File "C:\Users\Administrator\Desktop\bot\plugins\sagiri-bot-3.1.2\main.py", line 23, in <module>
    os.mkdir(f"{os.getcwd()}/log/{datetime.now().strftime('%Y-%m-%d')}")
    │  └ <built-in function mkdir>
    └ <module 'os' from 'C:\\ProgramData\\Anaconda3\\lib\\os.py'>

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\Administrator\\Desktop\\bot\\plugins\\sagiri-bot-3.1.2/log/2022-04-29'
```
![image](https://user-images.githubusercontent.com/104503043/165949730-370295dd-b0f0-4d0b-b515-6b99c081e942.png)

**Comment by nullqwertyuiop** [comment]
尝试使用 `git clone https://github.com/SAGIRI-kawaii/sagiri-bot` 代替直接下载 release

已在 c40d6e147a7452e2d72c0ac4047b38d1e419f575 中修复

**Comment by nullqwertyuiop** [comment]
手动解决方法：直接在启动目录下建立 `log` 文件夹

**Comment by WindraiteLesd** [comment]
想复杂了哈哈，原来就是缺个文件夹的事
