### ISSUE TITLE
wordle 猜词与已知命令ph冲突

### ISSUE THREAD

**Issue by hcxx** [SAGIRI-kawaii/sagiri-bot#240]
**问题**
在进行wordle 猜词时会与已知命令冲突，例如phone单词与ph命令冲突，导致无法猜测该单词。

**如何复现**
1. 开启/wordle功能使用
2. 猜测单词phone

**预期行为**
正确猜测该单词

**Comment by nullqwertyuiop** [comment]
无法复现，请问该问题是否多次发生？
![2bd002b25a3006ee.jpg](https://user-images.githubusercontent.com/49110142/166617279-0953ddf0-374f-441d-9503-7d82fb1dfe85.jpg)

**Comment by SAGIRI-kawaii** [comment]
已经更新空格策略，尝试 `git pull` 更新
