### ISSUE TITLE
使用user -grant 时member_id超过限制

### ISSUE THREAD

**Issue by CmpveYoo** [SAGIRI-kawaii/sagiri-bot#25]
mysql中member_id的类型为 **int**
导致无法存入大于2147483648的QQ号
报错：1264 Out of range value for column
用mysql-alter的修改命令参考（https://www.runoob.com/mysql/mysql-alter.html）
将其类型改为**bigint**后就可以正常使用
![image](https://user-images.githubusercontent.com/45991818/117790203-b60da080-b27b-11eb-9149-8374c5cc5a3f.png)

非常好的机器人，作者加油！

**Comment by SAGIRI-kawaii** [comment]
已经上传了最新版本，可否帮忙测试下mysql兼容性？

**Comment by CmpveYoo** [comment]
👌，今晚试试

**Comment by CmpveYoo** [comment]
requirements要加个 'aiosqlite'
但安装了aiosqlite 之后还是报错
[common.log](https://github.com/SAGIRI-kawaii/sagiri-bot/files/6466657/common.log)
[error.log](https://github.com/SAGIRI-kawaii/sagiri-bot/files/6466659/error.log)
去看了mysql然后
![image](https://user-images.githubusercontent.com/45991818/117988313-e0d82180-b36d-11eb-9a1a-041fbd9119ea.png)
不让登陆...重启还是登不上，我去修mysql了

**Comment by SAGIRI-kawaii** [comment]
push时最后一次没有推上，可以先在SAGIRIBOT.Core.AppCore 中第121行try下面加入await orm.create_all()

**Comment by CmpveYoo** [comment]
ok了

**Comment by SAGIRI-kawaii** [comment]
> requirements要加个 'aiosqlite'
> 但安装了aiosqlite 之后还是报错
> [common.log](https://github.com/SAGIRI-kawaii/sagiri-bot/files/6466657/common.log)
> [error.log](https://github.com/SAGIRI-kawaii/sagiri-bot/files/6466659/error.log)

数据库异步库要自行安装自己所使用数据库的，如mysql则安装aiomysql，在README中数据库连接配置部分有提到
