### ISSUE TITLE
解压mcl-2.1.0.zip，执行./mcl 提示错误

### ISSUE THREAD

**Issue by Wxrmr** [SAGIRI-kawaii/sagiri-bot#255]
**问题**
2022-05-27 10:59:57 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-05-27 10:59:57 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-05-27 10:59:57 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-05-27 10:59:57 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
**如何复现**
如何复现错误.

**预期行为**
你希望如何更改/原本应该是怎样的.

**使用环境:**
lunix
- 系统:
Debian11.6 64bit
java -version      openjdk version "11.0.15" 2022-04-19
javac -version    javac 11.0.15
**日志/截图**
![8 JY7Y~T2UQE}IR9XFJS)`A](https://user-images.githubusercontent.com/106142304/170624967-a8c5a2f3-196b-4d49-9cd8-28624ad2bf0a.png)
![image](https://user-images.githubusercontent.com/106142304/170625031-8ceb361e-9de6-456e-95d3-c9a179dcf2db.png)

**Comment by nullqwertyuiop** [comment]
无视即可。另：是 `linux` 不是 `lunix`

**Comment by Wxrmr** [comment]
![image](https://user-images.githubusercontent.com/106142304/170680084-c0d8a963-608d-4ae4-a8f7-10082328df00.png)
复制文档上的数据更改MCL/config/net.mamoe.mirai-api-http/setting.yml目录下的文件后执行./mcl还是在这个页面

**Comment by nullqwertyuiop** [comment]
请按照文档所写步骤进行部署，谢谢。
由给出的日志看来，下一步应该进行 [登录QQ](https://sagiri-kawaii.github.io/sagiri-bot/deployment/linux/#qq) 以及 [配置自动登录](https://sagiri-kawaii.github.io/sagiri-bot/deployment/linux/#_5)。
另：不建议mirai-api-http 监听端口设置为 8080，在某些情况下这可能造成无法正常连接的情况（见 [Address in use](https://sagiri-kawaii.github.io/sagiri-bot/FAQ/#address-in-use) 与 [adapter down](https://sagiri-kawaii.github.io/sagiri-bot/FAQ/#adapter-down)）

从 Windows 版邮件发送

发件人: Wxrmr
发送时间: 2022年5月27日 18:15
收件人: SAGIRI-kawaii/sagiri-bot
抄送: Null; Comment
主题: Re: [SAGIRI-kawaii/sagiri-bot] 解压mcl-2.1.0.zip，执行./mcl 提示错误 (Issue #255)


复制文档上的数据更改MCL/config/net.mamoe.mirai-api-http/setting.yml目录下的文件后执行./mcl还是在这个页面

**Comment by SAGIRI-kawaii** [comment]
此错误可无视

**Comment by Wxrmr** [comment]
![image](https://user-images.githubusercontent.com/106142304/170690636-90d3a123-5da0-43b2-9789-b2533812b06b.png)
输入./mcl命令是在此文件下执行么
![image](https://user-images.githubusercontent.com/106142304/170690760-62113aaf-c4ca-4f86-a9aa-6c6878f1cb28.png)

**Comment by Wybxc** [comment]
> ![image](https://user-images.githubusercontent.com/106142304/170690636-90d3a123-5da0-43b2-9789-b2533812b06b.png) 输入./mcl命令是在此文件下执行么 ![image](https://user-images.githubusercontent.com/106142304/170690760-62113aaf-c4ca-4f86-a9aa-6c6878f1cb28.png)

对，这个文件夹里的 `mcl` 文件就是启动脚本

**Comment by Wxrmr** [comment]
在此处执行./mcl会出现下方截图，不会出现Event: BotOnlineEvent(bot=Bot(<你的QQ号>))
![image](https://user-images.githubusercontent.com/106142304/170692036-e8fcf269-1ed5-49c3-aabb-2468ee2774ac.png)
配置为
![image](https://user-images.githubusercontent.com/106142304/170693538-a308b1dc-eb2e-4d07-913e-d4665fa0e32e.png)

**Comment by nullqwertyuiop** [comment]
请问是否已在 mcl 登录了 QQ？从日志上看似乎你并没有执行登录操作。

**Comment by Wxrmr** [comment]
没有出现登录QQ的操作，

**Comment by nullqwertyuiop** [comment]
![image](https://user-images.githubusercontent.com/49110142/170694732-7b3156a8-1ee0-4662-b385-d15ac4591ef9.png)

**Comment by SAGIRI-kawaii** [comment]
https://sagiri-kawaii.github.io/sagiri-bot/deployment/linux/#qq
文档里有写如何登录qq

**Comment by Wxrmr** [comment]
![Uploading image.png…]()
在此处输入所要登录的QQ么

**Comment by Wxrmr** [comment]
![image](https://user-images.githubusercontent.com/106142304/170699376-b2e49ea0-f45c-43d7-91bd-08eabce5cd70.png)
上方报错可以忽略么

**Comment by Wxrmr** [comment]
此处输入密码
![image](https://user-images.githubusercontent.com/106142304/170702741-0db51351-9882-4680-800f-309c216b8f2e.png)

执行./mcl后报错
![image](https://user-images.githubusercontent.com/106142304/170703278-00d3d9ba-673d-46b7-a050-7a25c8764d76.png)
![image](https://user-images.githubusercontent.com/106142304/170703304-8e7676fc-c50c-4dea-bd8e-dd0eed6c9369.png)

**Comment by SAGIRI-kawaii** [comment]
首先，截图注意隐私信息不要发出来
其次，密码应填写至password项下value的位置

**Comment by Wxrmr** [comment]
![image](https://user-images.githubusercontent.com/106142304/170736108-063bbc85-318d-4870-980a-9996c18a7f23.png)

激活虚拟环境时出现这个问题

**Comment by nullqwertyuiop** [comment]
[谷歌翻译](translate.google.com) [百度翻译](fanyi.baidu.com) [有道翻译](https://fanyi.youdao.com)

**Comment by lian-koishi** [comment]
首先，使用mirai前，这种登录是有文档的，你应该先查阅文档。关于如何登录你可以不需要更改文件，直接在mirai的控制台输入/help可以看到mirai的一些指令参数

**Comment by lian-koishi** [comment]
关于这种问题，你应该查阅mirai的使用手册，上面明确对于登录这种问题都有明确说明。如果你连登录都不会的话，建议还是多看看mirai的使用手册

**Comment by nullqwertyuiop** [comment]
我的建议是，RTFM

**Comment by lian-koishi** [comment]
登录的话，直接改配置文件容易出错，建议在控制台输入login <账号> <密码>进行登录，注意空格，登录如果弹出验证请把mirai发送的链接复制到浏览器进行扫码验证，完成后即可登录，如果你想要自动登录，请后续自行查阅mirai手册或者在mirai启动的环境下发送/help查看帮助

**Comment by SAGIRI-kawaii** [comment]
> ![image](https://user-images.githubusercontent.com/106142304/170736108-063bbc85-318d-4870-980a-9996c18a7f23.png)
> 
> 激活虚拟环境时出现这个问题

上面不是写了解决方法吗

**Comment by yumibiao** [comment]
如果mirai出现登录失败的情况，可以尝试使用这个项目来解决。https://github.com/mzdluo123/TxCaptchaHelper

同时，mirai可以直接使用/login命令来进行登录。
在没有看懂配置文件的情况下，还是建议不要直接修改，防止各种程序读取配置文件出错，以及一系列的问题。

在看不懂报错信息的情况下，可以尝试使用免费的翻译软件尝试翻译。有些时候报错会直接告诉您怎么做。
