### ISSUE TITLE
[Feature Request]功能请求的内容

### ISSUE THREAD

**Issue by dongbao66** [SAGIRI-kawaii/sagiri-bot#264]
1.apex查询；--------https://github.com/Shennoter/ApexRankLookUp
2.原神体力、派遣查询；------------https://github.com/HibiKier/zhenxun_bot
3.b站主播订阅；----------同 zhenxunbot
4.与机器人的好感度（例如签到增加等）----同 zhenxunbot

**Comment by MingxuanGame** [comment]
apex 查询本身为 mirai console 插件，可直接安装

**Comment by dongbao66** [comment]
你好，我最近忙碌中，无法亲自回复你的邮件。我看到后会尽快给你回复。
