### ISSUE TITLE
bot启动失败力

### ISSUE THREAD

**Issue by TDuckQWQ** [SAGIRI-kawaii/sagiri-bot#265]
![image](https://user-images.githubusercontent.com/62102282/171848087-1a57c780-72c4-4354-aadb-3c7fb01c9920.png)
这是为啥子..

**Comment by nullqwertyuiop** [comment]
请确保已安装完成所有依赖。

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/171848645-595b76d9-bf57-4938-9a4e-355c4591af85.png)
唔....

**Comment by nullqwertyuiop** [comment]
请尝试安装 VC++，如安装后仍无法继续，尝试移除 `requirements.txt` 中的 `wordcloud` 并重试。

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/171849486-58c01760-74cf-4098-87c7-6efeb22492da.png)
嘛 移除了.... 然后成这样子了

**Comment by nullqwertyuiop** [comment]
请**按照文档所写步骤进行部署**，谢谢配合。
