### ISSUE TITLE
在config设置了host_qq，但似乎没有权限

### ISSUE THREAD

**Issue by WKyouka** [SAGIRI-kawaii/sagiri-bot#268]
在manage.md中说：
注：等级4的账户将在机器人初始化时就存入数据库，对应成员id为 `config.yaml` 中所填入的 `bot_qq` 项
但是bot_qq是机器人的账号吧，改了这个值是无法连接上的，但是改host_qq又毫无作用
所以来询问下权限等级是怎么获得的？

**Comment by nullqwertyuiop** [comment]
需要注意的是，在不改动数据库的情况下，仅有 `host_qq` 拥有等级 `4` 的权限，而非 `bot_qq`。

**Comment by WKyouka** [comment]
> 需要注意的是，在不改动数据库的情况下，仅有 `host_qq` 拥有等级 `4` 的权限，而非 `bot_qq`。

但是我设置了host_qq后，输入setting -set speakMode=rainbow时，返回了speakMode=rainbow | 权限不足，要求权限等级3， 以及我在user -grant @X  3时，返回了权限不足，爬!。我不大清楚是不是哪里出了问题。

后续测试了一下，应该是我在第一次启动的时候设置了其他host_qq，但是第二次修改了这个值，但是似乎再修改不起作用？

**Comment by nullqwertyuiop** [comment]
暂时无法复现，尝试删除已生成的数据库并重新启动？
`app_core` 中权限相关代码如下，理应不会出现 `host_qq` 权限不为 `4` 的问题。
https://github.com/SAGIRI-kawaii/sagiri-bot/blob/ec58b1b99ca896c4b243ef2eb6662e042d8c5a0b/sagiri_bot/core/app_core.py#L178-L183

**Comment by WKyouka** [comment]
> 暂时无法复现，尝试删除已生成的数据库并重新启动？ `app_core` 中权限相关代码如下，理应不会出现 `host_qq` 权限不为 `4` 的问题。
> 
> https://github.com/SAGIRI-kawaii/sagiri-bot/blob/ec58b1b99ca896c4b243ef2eb6662e042d8c5a0b/sagiri_bot/core/app_core.py#L178-L183

似乎可以了，可能是之前转移文件时出了点问题吧
