### ISSUE TITLE
有无可取消bot回复命令的设置

### ISSUE THREAD

**Issue by Sulfuriclogic** [SAGIRI-kawaii/sagiri-bot#271]
比如我发“已加载插件”，bot会以回复的形式发出结果，想要取消这样给出结果的形式

**Comment by nullqwertyuiop** [comment]
将 `sagiri_bot/handler/required_module/saya_manager/__init__.py` 中所有 `QuoteSource` 替换为 `Normal` 即可

**Comment by Sulfuriclogic** [comment]
谢谢大佬，这边基础改好了，还有就是例如meme趣味表情包依旧会回复该如何取消，找过memes.py文件无QuoteSource

**Comment by nullqwertyuiop** [comment]
https://github.com/SAGIRI-kawaii/sagiri-bot/blob/Ariadne/sagiri_bot/handler/handlers/memes.py#L94-L98
去除 quote 参数即可
