### ISSUE TITLE
启动后Sagiri-Bot只能收到一条消息，且程序不对后续操作做出回应

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#28]
如题，sagiri-bot的error.log内容为空，就自己把控制台的内容拷出来了
[sagiri.log](https://github.com/SAGIRI-kawaii/sagiri-bot/files/6467323/sagiri.log)

一开始以为是用了老版本的数据库导致的，后来发现换新的数据库也是这样

环境：Debian Buster x64, Python3.8, MySQL

**Comment by nullqwertyuiop** [comment]
不小心点到回车了，在码了

**Comment by nullqwertyuiop** [comment]
貌似是数据库没连上(?)，用新的数据库跑什么也没写进去
```
# config.yaml
DBLink: mysql+aiomysql://databaseName:passwd@localhost:3306/databaseName
```

**Comment by SAGIRI-kawaii** [comment]
数据库是否创建成功？

**Comment by nullqwertyuiop** [comment]
否(?)，数据库大小始终为 0.00b

**Comment by SAGIRI-kawaii** [comment]
了解了，请尝试将SAGIRIBOT.ORM.AsyncORM中第29行取消注释并将第30行注释，这应该是误留下的测试语句

**Comment by nullqwertyuiop** [comment]
问题解决。但是直接用空数据库跑仍会报错，使用旧数据库则可以顺利运行

**Comment by SAGIRI-kawaii** [comment]
请查看SAGIRIBOT.Core.AppCore 中第121行try下有无await orm.create_all()！若没有请更新最新版本

**Comment by nullqwertyuiop** [comment]
有，已是最新版。

**Comment by nullqwertyuiop** [comment]
找到报错原因了，图方便直接把旧版config.yaml拷过来了。启动后因缺少 loliconApiKey 行报错而不进行后续操作
我的错
