### ISSUE TITLE
[other_issue]缩写查询敏感词机器人会回复

### ISSUE THREAD

**Issue by XiaoDouZiQwQ** [SAGIRI-kawaii/sagiri-bot#281]
例如
缩 tsky

可能的结果:

tsky => 通商宽衣

**Comment by nullqwertyuiop** [comment]
这个就没办法了......
除非@SAGIRI-kawaii 再写一个通用的内容审核，然后 API 取回的数据过一次审

**Comment by nullqwertyuiop** [comment]
i mean 工具无罪

**Comment by XiaoDouZiQwQ** [comment]
确实 主要是怕机器人账户消失，我自己目前的解决办法就是禁用掉这个插件
