### ISSUE TITLE
[Bug Report]图片显示异常

### ISSUE THREAD

**Issue by 1027NASA** [SAGIRI-kawaii/sagiri-bot#289]
**问题**
运行SAGIRI-BOT时，原神相关资源下载失败，并显示“没有找到 xxx的ID 更新 xxx 图标失败”

而后在QQ上进行“原神10连抽”指令时，文字显示正常，但图片无法显示。

**如何复现**
如何复现错误.

**预期行为**
你希望如何更改/原本应该是怎样的.

**使用环境:**

- 系统:
- MAH 版本:
- Ariadne 版本:
- Python 版本:3.8.9
- 源码版本:
- 其他 Graia 库版本:
- 其他 有关 库版本:

**日志/截图**
将任何有关的日志/截图放到这里（控制台输出/MAH 输出/...)
![IMG_1508](https://user-images.githubusercontent.com/87003032/183613827-a1c9bee8-f38f-48b2-a49b-eb26bc50e1ec.jpeg)
![IMG_1507](https://user-images.githubusercontent.com/87003032/183613859-d86f9e78-594f-44c5-8e24-bb0edb2af284.jpeg)

**Comment by SAGIRI-kawaii** [comment]
原神插件因api变动即将移除，不影响其他插件
