### ISSUE TITLE
[Bug Report] 在群内启用骰子功能后掷骰子bot回复“骰子功能尚未开启哟~”

### ISSUE THREAD

**Issue by cold233** [SAGIRI-kawaii/sagiri-bot#341]
### 问题

在群内启用骰子功能后掷骰子bot回复“骰子功能尚未开启哟~”

### 如何复现

环境：linux Linux armbian 5.15.62-flippy-76+o #168 SMP PREEMPT Sun Aug 21 22:25:51 CST 2022 aarch64 GNU/Linux
Python 3.9.2
MiraiConsole v2.12.1
Plugins: net.mamoe.mirai-api-http v2.6.1, Minecraft MOTD Fetcher v1.1.8, Chat Command v0.5.0, EntryLib v1.3.2, MCL Addon v2.0.2
复现步骤：正常部署机器人，加入群，打开骰子插件，发送1d6

### 预期行为

应该能正常掷骰子

### 使用环境

```markdown
见上文
```

### 日志/截图

![屏幕截图 2022-09-16 101546](https://user-images.githubusercontent.com/54432054/190541962-03eb61d5-17d3-45ad-9fdc-b178c0798ab5.png)

**Comment by nullqwertyuiop** [comment]
`dice` 插件拥有单独开关，尝试发送 `setting -set dice=True` 再进行测试？

**Comment by cold233** [comment]
解决了，但咋没在相关教程里看到说明呢23333不知道在哪能看到这些设置项呢？

**Comment by nullqwertyuiop** [comment]
请阅读[文档](https://sagiri-kawaii.github.io/sagiri-bot/manage/)，谢谢。
