### ISSUE TITLE
前端管理面板建议收集

### ISSUE THREAD

**Issue by SAGIRI-kawaii** [SAGIRI-kawaii/sagiri-bot#358]
近期可能要写后台面板，如果对功能/样式或其他方面有什么建议都可以发到这里

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by I-love-study** [comment]
自定义页面背景，最好还能随机涩涩（

**Comment by SAGIRI-kawaii** [comment]
（？
