### ISSUE TITLE
[Feature Request] 迁移至 nonebot2

### ISSUE THREAD

**Issue by BlueGlassBlock** [SAGIRI-kawaii/sagiri-bot#362]
### 请求内容

迁移到 nonebot2

### 实现逻辑

替换 graia 为 nonebot2

### 请求原因

鉴于上游仓库 GraiaProject/Ariadne 已经存档，建议迁移到 nonebot2

### 实现参考

<https://github.com/HiBiKier/zhenxun_bot>

**Comment by SAGIRI-kawaii** [comment]
Reject.
