### ISSUE TITLE
Python 3.11 支持

### ISSUE THREAD

**Issue by I-love-study** [SAGIRI-kawaii/sagiri-bot#369]
依赖的第三方库有不支持py3.11的（如wordcloud）
留档，哪天支持了我就关

---
目前不支持 3.11 的库（ √ 为现已支持）

- [x] **所有**基于 torch 的插件（mockingbird, super_resolution），~~需要等到 [torch](https://github.com/pytorch/pytorch) 1.14.0~~ 卧槽直接发 2.0.0 了
- [x] mockingbird 依赖的 libsora 依赖的 numba，需要等到 [numba](https://github.com/numba/numba) 0.57.0
- [x] wordcloud 依赖的 [wordcloud](https://github.com/amueller/word_cloud)，虽然没有 whl，但能够编译通过了

**Comment by SAGIRI-kawaii** [comment]
没事，我还没写词云（x

**Comment by I-love-study** [comment]
https://github.com/SAGIRI-kawaii/sagiri-bot/blob/31d0705f8c2821f21cea4c8877e2ece094d52156/pyproject.toml#L18

都写 require 里面力

**Comment by nullqwertyuiop** [comment]
~~意思是先扬了 `wordcloud` 吗~~

**Comment by I-love-study** [comment]
> ~~意思是先扬了 `wordcloud` 吗~~

等`wordcloud`那边的 pr merge 罢
他们都在催（

**Comment by I-love-study** [comment]
wordcloud 当前情况：
因为那test代码里面有一个 np.int 已经 deprecated 了，虽然仓库支持了，但是 action 不发版
不过考虑到裸连github太慢了，暂时就不把wordcloud依赖换成github了
