### ISSUE TITLE
[Bug Report] Webscoket connection closed

### ISSUE THREAD

**Issue by CloudPLayer01** [SAGIRI-kawaii/sagiri-bot#370]
### 问题

首次启动时ws无法链接，mcl与msh启动成功，msh与config配置正常。

### 使用环境

```markdown
- 系统: Ubuntu20.04
- mirai 版本: 2.13.2
- mirai-api-http 版本: 2.6.2
- Python 版本: 3.10
- 源码版本: SAGIRI-BOT V4.0.0-pre
```

### 日志/截图

[2022-12-19.log](https://github.com/SAGIRI-kawaii/sagiri-bot/files/10255779/2022-12-19.log)
[log.txt](https://github.com/SAGIRI-kawaii/sagiri-bot/files/10255794/log.txt)

mirai_host: http://127.0.0.1:7713

adapters:
  - http
  - ws

enableVerify: true
verifyKey: 1234567890

debug: false

singleMode: false

cacheSize: 4096

adapterSettings:
  http:
    host: 127.0.0.1
    port: 7713
    cors: ["*"]
  
  ws:
    host: 127.0.0.1
    port: 7713
    reservedSyncId: -1

**Comment by nullqwertyuiop** [comment]
猜您想搜：FAQ

**Comment by CloudPLayer01** [comment]
faq两个关于ws的都看过了

**Comment by SAGIRI-kawaii** [comment]
重启mcl后再打开bot试试
