### ISSUE TITLE
看起来像是多线程报错

### ISSUE THREAD

**Issue by lancer-wang** [SAGIRI-kawaii/sagiri-bot#38]
![image](https://user-images.githubusercontent.com/69783837/119446869-aa34da80-bd61-11eb-9f69-0762016b0153.png)
原因不明,但是貌似机器人能正常使用

**Comment by lancer-wang** [comment]
然后获取三次元图片的时候报这个
![image](https://user-images.githubusercontent.com/69783837/119448367-d18ca700-bd63-11eb-9b63-c7e4a71408e3.png)

**Comment by SAGIRI-kawaii** [comment]
请问版本？

**Comment by SAGIRI-kawaii** [comment]
另外三次元图库是否有图片？

**Comment by lancer-wang** [comment]
Python 3.8 java11
系统centos8 
机器人为最新版本
三次元貌似是因为没图,没仔细看,以为三次元图是获取到的,结果是本地的

**Comment by SAGIRI-kawaii** [comment]
目前我尚未碰到过这个问题，不过报错显示是可视化管理模块的问题，若不使用前端管理页面的话可以忽略这个错误，若需要使用的话出现报错后api是否可以正常启动？

**Comment by lancer-wang** [comment]
本地没有报错,可能就是可视化的问题吧
