### ISSUE TITLE
qq登录不了，一直卡这一步了。

### ISSUE THREAD

**Issue by royuki2431** [SAGIRI-kawaii/sagiri-bot#381]
请问一下这个是什么问题，每次验证完之后都是登录失败。
![Snipaste_2023-01-16_22-37-09](https://user-images.githubusercontent.com/93425616/212704344-8de06c65-79ba-4c0d-990e-cff6f562d29c.png)

**Comment by nullqwertyuiop** [comment]
风控

**Comment by SAGIRI-kawaii** [comment]
尝试 [登录报错，提示“服务连接中，请稍后再试](https://github.com/mamoe/mirai/issues/2426) 中的解决方法，如更换协议，降级等，若还不行等待mirai修复，或换一个号试试

**Comment by royuki2431** [comment]
无法修改这个文件AutoLogin.yml想改为 `protocol: IPAD`，启动后自动复原了
![Sni3](https://user-images.githubusercontent.com/93425616/212716005-bbf210c4-48b7-4619-8635-37ae232c679f.png)

**Comment by nullqwertyuiop** [comment]
> 无法修改这个文件AutoLogin.yml想改为 `protocol: IPAD`，启动后自动复原了
> ![Sni3](https://user-images.githubusercontent.com/93425616/212716005-bbf210c4-48b7-4619-8635-37ae232c679f.png)
> 

请阅读部署文档。

不应在 `mcl` 已启动时修改 `AutoLogin.yml`，可尝试使用控制台内建的 `autoLogin` 指令修改登录协议。

如需要手动修改，请在未启动时编辑。
