### ISSUE TITLE
[Bug Report] Torch 在 arm64 + poetry 环境中无法正确安装

### ISSUE THREAD

**Issue by I-love-study** [SAGIRI-kawaii/sagiri-bot#383]
### 问题

arm64 无法通过 poetry 安装 torch
相关pr ~~https://github.com/pytorch/pytorch/pull/91083~~ https://github.com/pytorch/pytorch/pull/93066
临时解决方案 https://github.com/SAGIRI-kawaii/sagiri-bot/pull/382

### 如何复现

1. 在 arm64 的配件中安装 torch

### 预期行为

能够成功安装

**Comment by I-love-study** [comment]
别下次更新 `poetry.lock` 又忘了（

**Comment by nullqwertyuiop** [comment]
> 别下次更新 `poetry.lock` 又忘了（

应该没问题？
https://github.com/SAGIRI-kawaii/sagiri-bot/pull/392
