### ISSUE TITLE
在群内发送含Emoji的消息时报错

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#40]
如题，报错内容见文件。
[error_log.log](https://github.com/SAGIRI-kawaii/sagiri-bot/files/6561560/error_log.log)

**Comment by nullqwertyuiop** [comment]
不小心回车了 在写了

**Comment by SAGIRI-kawaii** [comment]
目前看来应该是mysql字符编码的问题，回去看下

**Comment by nullqwertyuiop** [comment]
解决方案：
MySQL 排序方式使用 utf8mb4，使用 dynamic 代替 compact
