### ISSUE TITLE
[Bug Report] <title>无法启动机器人

### ISSUE THREAD

**Issue by Zzx108** [SAGIRI-kawaii/sagiri-bot#406]
### 问题

在使用命令启动机器人时报错
第一次写这个...我看上一个人也是这个，但是我还是没有解决

### 如何复现

1.使用环境：Windows Server 2022   python:3.10.10    git:2.39.2
2.poetry shell → python main.py
3.报错：未检测到git     name 'Repo' is not defined
4.尝试使用 poetry run python main.py 运行。依然报错
5.git根据网上教程配置了环境变量，是克隆的，并且git pull正常。

### 日志/截图

PS C:\Users\Administrator\Desktop\Zzx\sagiri-bot> poetry run python main.py
2023-02-19 21:16:52.198 | ERROR    | shared.utils.self_upgrade:<module>:16 - 未检测到git！
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Zzx\sagiri-bot\main.py", line 31, in <module>
    from core import Sagiri
  File "C:\Users\Administrator\Desktop\Zzx\sagiri-bot\core\__init__.py", line 47, in <module>
    from shared.utils.self_upgrade import UpdaterService
  File "C:\Users\Administrator\Desktop\Zzx\sagiri-bot\shared\utils\self_upgrade.py", line 23, in <module>
    def get_current_repo() -> Repo | None:
NameError: name 'Repo' is not defined. Did you mean: 'repr'?

**Comment by nullqwertyuiop** [comment]
由报错推测为 `GitPython` 未正常安装，请运行 `poetry show GitPython` 并附上输出内容，谢谢。

**Comment by Zzx108** [comment]
> 由报错推测为 `GitPython` 未正常安装，请运行 `poetry show GitPython` 并附上输出内容，谢谢。
输出内容如下
 name         : gitpython
 version      : 3.1.30
 description  : GitPython is a python library used to interact with Git repositories

dependencies
 - gitdb >=4.0.1,<5

**Comment by Zzx108** [comment]
> 由报错推测为 `GitPython` 未正常安装，请运行 `poetry show GitPython` 并附上输出内容，谢谢。
 你好，输出内容如下
 name         : gitpython
 version      : 3.1.30
 description  : GitPython is a python library used to interact with Git repositories

dependencies
 - gitdb >=4.0.1,<5
