### ISSUE TITLE
[Bug Report] 无法启动机器人Traceback (most recent call last)

### ISSUE THREAD

**Issue by tangjiang59** [SAGIRI-kawaii/sagiri-bot#412]
### 问题

按照教程在进行到配置 alembic这一步骤时，使用python main.py命令启动机器人时出现报错，
无法启动机器人，也无法生成alembic.ini
mcl可以正常启动并使用

### 如何复现

1.使用环境 Debian 11.6，Python 3.10.4
2.使用Anaconda,使用虚拟环境，poetry是pip安装的，config.yaml仅修改了bot_accounts和host_qq
3.运行了python main.py
4.错误报告如下图

### 使用环境

```markdown
- 系统: 
- mirai 版本: 
- mirai-api-http 版本: 
- Python 版本: 
- 源码版本: 
- 其他 Graia 库版本:
- 其他 有关 库版本:
```

### 日志/截图

![DRPNJVMM_PWT@7V@H8NAC}O](https://user-images.githubusercontent.com/34938651/224554482-091a0a31-56ee-4278-b187-6309cd09b4de.png)
![PCXJQ0 `__X@W)@)@@`R515](https://user-images.githubusercontent.com/34938651/224554483-1d993795-9db3-4570-b44e-8911e5c22c53.png)

**Comment by nullqwertyuiop** [comment]
请先阅读 FAQ

**Comment by SAGIRI-kawaii** [comment]
- bot_accounts为列表
- default_account为bot_accounts中的值
- 上述信息在[文档](https://sagiri-kawaii.github.io/sagiri-bot/configuration/#configyaml)和[FAQ](https://sagiri-kawaii.github.io/sagiri-bot/FAQ/#pydanticerror_wrappersvalidationerror)中都有，请仔细查看，善用搜索
