### ISSUE TITLE
管理号在新加入的群内权限不为4，重启 Sagiri-Bot 后恢复权限

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#42]
如图，新建群、新加群效果相同
![0851B96A-4222-4C7D-A37F-CA72B887B781](https://user-images.githubusercontent.com/49110142/120004475-649a3b00-c009-11eb-8fc0-7dc5d458abb9.png)
貌似是数据库中表chat_session在机器人加入新群后没有随后更新导致的？

一小时开了3个issue，感觉挺不好意思的.jpg

**Comment by SAGIRI-kawaii** [comment]
我确实没有写新加群的权限设置，之后会加上

**Comment by SAGIRI-kawaii** [comment]
fixed
