### ISSUE TITLE
[Feature Request] PDM Support

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#426]
### 请求内容

开个 issue 先，晚点试试写了

### 实现逻辑

记得写 pyproject.toml 里面可以和 poetry 共存（？）
不清楚，先试试

### 请求原因

poetry 解析一次半小时有点顶不住

### 实现参考

https://github.com/Little-LinNian/RainAa/commit/d72c681ed26c96e4e3ab02941e6844f745d189ce

**Comment by Silverovo** [comment]
看看你的
