### ISSUE TITLE
 请问我这是遇到了什么问题呀？

### ISSUE THREAD

**Issue by Exmachina-V** [SAGIRI-kawaii/sagiri-bot#43]
![image](https://user-images.githubusercontent.com/74316230/120082453-c932c400-c0f5-11eb-9334-321c5ffcf667.png)

**Comment by Exmachina-V** [comment]
bot成功发出了打卡上班的消息，但不能响应我

**Comment by Exmachina-V** [comment]
您的requirements.txt依赖文件里貌似少了graia-schedualer

**Comment by Exmachina-V** [comment]
![image](https://user-images.githubusercontent.com/74316230/120082751-3abf4200-c0f7-11eb-85b4-c304faa74cf6.png)
控制台是这样的，加载Handler数量为0？

**Comment by SAGIRI-kawaii** [comment]
Handlers加载为0是正常的，前端还未修改，前面的报错可能是graia的问题，我回去查看下我的版本看看

**Comment by SAGIRI-kawaii** [comment]
> bot成功发出了打卡上班的消息，但不能响应我

不能响应是哪个功能啊

**Comment by Exmachina-V** [comment]
就是我发任何信息都会报上面的错

**Comment by Exmachina-V** [comment]
是garai库没安好或版本问题吗

**Comment by SAGIRI-kawaii** [comment]
应该是的，这是我的graia版本，请卸载graia后按版本号重新安装下试试
```
graia-application-mirai   0.18.4
graia-broadcast           0.8.10
graia-saya                0.0.8
```

**Comment by Exmachina-V** [comment]
我之前下了requirements.txt里的依赖后，他还报错说少了graia.schedualer

**Comment by Exmachina-V** [comment]
> 应该是的，这是我的graia版本，请卸载graia后按版本号重新安装下试试
> 
> ```
> graia-application-mirai   0.18.4
> graia-broadcast           0.8.10
> graia-saya                0.0.8
> 好的，我去试试

**Comment by Exmachina-V** [comment]
安装这个版本还是会报一样的错

**Comment by Exmachina-V** [comment]
> 安装这个版本还是会报一样的错

![image](https://user-images.githubusercontent.com/74316230/120089991-aaeab980-c131-11eb-8f22-79d84161a733.png)

**Comment by Exmachina-V** [comment]
![image](https://user-images.githubusercontent.com/74316230/120090223-6eb85880-c133-11eb-982e-c2034271ca3f.png)
![image](https://user-images.githubusercontent.com/74316230/120090235-82fc5580-c133-11eb-9cfd-7eee71169a6b.png)

**Comment by Exmachina-V** [comment]
不报错了，但是不回复，我config.yaml里只填了lolicon和腾讯的api，数据库没连

**Comment by SAGIRI-kawaii** [comment]
尝试下 `来点纱雾色图`?
另外若不使用mysql数据库则将 `config.yaml` 中 `DBLink` 改为 `sqlite+aiosqlite:///data.db` 即可

**Comment by Exmachina-V** [comment]
![image](https://user-images.githubusercontent.com/74316230/120090380-8e9c4c00-c134-11eb-8ca8-34408d726552.png)
是这样吗，这样报错连不到数据库，我mysql数据库密码为空

**Comment by SAGIRI-kawaii** [comment]
目前mysql兼容并未完成，请先使用sqlite
`DBLink: sqlite+aiosqlite:///data.db`

**Comment by Exmachina-V** [comment]
请问一定要连上数据库才可以回消息吗

**Comment by SAGIRI-kawaii** [comment]
没有尝试过不连接数据库

**Comment by Exmachina-V** [comment]
那我先去下sqlite,辛苦大大了

**Comment by Exmachina-V** [comment]
![image](https://user-images.githubusercontent.com/74316230/120090638-ab398380-c136-11eb-9dae-5c8690bc4e57.png)
sqlite数据库里是空的，要导入啥表吗

**Comment by Exmachina-V** [comment]
![image](https://user-images.githubusercontent.com/74316230/120090668-e045d600-c136-11eb-982d-b2ba81ade6e4.png)
![image](https://user-images.githubusercontent.com/74316230/120090678-ed62c500-c136-11eb-96f0-09fe8c97203e.png)

**Comment by Exmachina-V** [comment]
我错了55555555

**Comment by Exmachina-V** [comment]
我直接连的data.db也不行 
![image](https://user-images.githubusercontent.com/74316230/120090829-133c9980-c138-11eb-9af1-8f000bd51843.png)

**Comment by Exmachina-V** [comment]
启动后第一次发任何消息都会websocket断开连接

**Comment by SAGIRI-kawaii** [comment]
ws断开连接是因为你关闭了前端页面，不影响什么

**Comment by Exmachina-V** [comment]
纱雾还是不理我5555

**Comment by SAGIRI-kawaii** [comment]
你发送什么命令了，有common.log文件吗

**Comment by Exmachina-V** [comment]
[common.log](https://github.com/SAGIRI-kawaii/sagiri-bot/files/6566225/common.log)

**Comment by Exmachina-V** [comment]
[error.log](https://github.com/SAGIRI-kawaii/sagiri-bot/files/6566226/error.log)

**Comment by Exmachina-V** [comment]
我就正常发消息，log里有记录

**Comment by SAGIRI-kawaii** [comment]
data.db有内容吗

**Comment by Exmachina-V** [comment]
没有，里面的表都是空的

**Comment by Exmachina-V** [comment]
![image](https://user-images.githubusercontent.com/74316230/120105008-bff33700-c189-11eb-8fc3-532541c128ff.png)
好像发现了

**Comment by Exmachina-V** [comment]
只setting和user_permission里有

**Comment by SAGIRI-kawaii** [comment]
chat_record 里呢？

**Comment by Exmachina-V** [comment]
空的
![image](https://user-images.githubusercontent.com/74316230/120105561-05b0ff00-c18c-11eb-92a3-4c8abc79d515.png)

**Comment by SAGIRI-kawaii** [comment]
空的？

**Comment by Exmachina-V** [comment]
里面就是这样的，布吉岛怎么回事

**Comment by SAGIRI-kawaii** [comment]
log文件看不出异常，确定所有功能无法使用？

**Comment by Exmachina-V** [comment]
我的状况就是成功启动后跳转到前端，bot发出打卡上班消息，然后我开始发消息，但是bot不会回，控制台有消息记录如：收到xxx群xxx的消息：xxxx

**Comment by SAGIRI-kawaii** [comment]
正常就是不会回的，你需要发送特定功能语句才会有回复，具体查看 docs/functions.md

**Comment by Exmachina-V** [comment]
![image](https://user-images.githubusercontent.com/74316230/120110869-fdfc5500-c1a1-11eb-885a-de788c9c49e7.png)
木得用

**Comment by SAGIRI-kawaii** [comment]
> ![image](https://user-images.githubusercontent.com/74316230/120110869-fdfc5500-c1a1-11eb-885a-de788c9c49e7.png)
> 木得用

有无bot界面截图，多试几个命令看看

**Comment by Exmachina-V** [comment]
bot界面截图是指？

**Comment by SAGIRI-kawaii** [comment]
main.py运行界面

**Comment by Exmachina-V** [comment]
![image](https://user-images.githubusercontent.com/74316230/120312323-294e8380-c30b-11eb-8745-a8e290a3e92e.png)
刚启动
![image](https://user-images.githubusercontent.com/74316230/120312596-85b1a300-c30b-11eb-8c7e-e66faff45ba2.png)
![image](https://user-images.githubusercontent.com/74316230/120312627-8f3b0b00-c30b-11eb-9d1c-e3051c2cd104.png)
输入命令

**Comment by SAGIRI-kawaii** [comment]
更新最新版后还会有此问题吗

**Comment by Exmachina-V** [comment]
![image](https://user-images.githubusercontent.com/74316230/121768478-fc169680-cb90-11eb-8fb6-2d792af64dd6.png)
现在连群组也不显示

**Comment by SAGIRI-kawaii** [comment]
目前的最新版呢？是否有过删除文件如 #52
