### ISSUE TITLE
无法从外网直接访问 Web 前端

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#46]
运行 Sagiri-Bot 且配置开启 Web 前端后，只能从本机访问 Web 前端，从外网无法访问。
分别将 /WebManager/web_manager.py 的第 99 行 与 /WebManager/websocket.py 的第 27 行中的 `127.0.0.1` 修改为本机外网 IP 地址后可正常访问。
希望后续版本能把这个写在配置文件中，让用户决定是否只可在本机访问。（能用 SSL 的话更好了，不用每次都切隐私模式）

**Comment by SAGIRI-kawaii** [comment]
目前尚未实现外网访问，只能在本机进行访问，之后可能会更新此功能

**Comment by SAGIRI-kawaii** [comment]
并入 #151
