### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by Air433up** [SAGIRI-kawaii/sagiri-bot#50]
运行后报错如下
![image](https://user-images.githubusercontent.com/60246381/121663165-b6969280-cad8-11eb-8289-b3fc052b85a5.png)

**Comment by SAGIRI-kawaii** [comment]
pydantic问题，尝试降级？
参考版本：
- pydantic                  1.7.1
- graia-application-mirai   0.17.3
- graia-broadcast           0.8.10
- graia-saya                0.0.8

**Comment by Air433up** [comment]
> ？pydantic问题，降级尝试
> 参考版本：
> 
> * pydantic 1.7.1
> * graia-application-mirai 0.17.3
> * graia-broadcast 0.8.10
> * graia-saya 0.0.8

似乎出现了新的问题
![image](https://user-images.githubusercontent.com/60246381/121759539-bb9b2680-cb58-11eb-827b-8a35edf12969.png)

**Comment by SAGIRI-kawaii** [comment]
`config.yaml` 中 `DBLink` 改为 `sqlite+aiosqlite:///data.db`

**Comment by Air433up** [comment]
> `config.yaml` 中 `DBLink` 改为 `sqlite+aiosqlite:///data.db`

已成功运行，感谢
