### ISSUE TITLE
模块显示加载成功，但是web页面没有内容

### ISSUE THREAD

**Issue by RONG-SONG** [SAGIRI-kawaii/sagiri-bot#51]
![图片](https://user-images.githubusercontent.com/48174107/121695990-3125d900-cafe-11eb-9312-6a25c377da50.png)
![图片](https://user-images.githubusercontent.com/48174107/121696005-35ea8d00-cafe-11eb-9157-f1d49124a704.png)

**Comment by nullqwertyuiop** [comment]
从浏览器的开发者工具里面看看控制台报了什么错

**Comment by RONG-SONG** [comment]
![图片](https://user-images.githubusercontent.com/48174107/121703539-874a4a80-cb05-11eb-9d72-5b0a4f90ed68.png)

**Comment by SAGIRI-kawaii** [comment]
使用的是火狐浏览器？

**Comment by RONG-SONG** [comment]
是的

**Comment by SAGIRI-kawaii** [comment]
尝试使用Chrome浏览器？可能我哪里写的有问题，前端还在学习中

**Comment by RONG-SONG** [comment]
Chrome一样的，你们不会吗？

**Comment by RONG-SONG** [comment]
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://localhost:8001/auth')
这个错误有影响吗

**Comment by SAGIRI-kawaii** [comment]
有详细报错嘛

**Comment by SAGIRI-kawaii** [comment]
看起来是mah验证的api，如果报错很可能导致机器人不能运行

**Comment by RONG-SONG** [comment]
请问这个认证我可以在哪个模块找到或者mah是什么？

**Comment by SAGIRI-kawaii** [comment]
mirai-api-http，你有启动mirai并成功启动mah嘛

**Comment by RONG-SONG** [comment]
我是用mirai-console-loader ，启动的时候有问题，最后应该是成功了
![图片](https://user-images.githubusercontent.com/48174107/121763861-c0200900-cb71-11eb-8209-2c3b867d9d51.png)
![图片](https://user-images.githubusercontent.com/48174107/121763864-c4e4bd00-cb71-11eb-8f52-bec069fbc9b3.png)

**Comment by SAGIRI-kawaii** [comment]
确定成功启动mirai-api-http?

**Comment by SAGIRI-kawaii** [comment]
最新版本2.6.6与mah可能有冲突，请降级至2.6.5并以mcl -u运行

**Comment by RONG-SONG** [comment]
shadiaoAppName，saucenaoApiKey这两个参数我没有修改，使用默认的，这个有影响吗

**Comment by SAGIRI-kawaii** [comment]
没有

**Comment by RONG-SONG** [comment]
我在mirai-console看到这样的说明，2.6.6是对2.6.5的bug修复，应该不会有特别大的影响吧

**Comment by SAGIRI-kawaii** [comment]
但是会对mah造成影响，确定mah已正确安装并成功启动？

**Comment by RONG-SONG** [comment]
第一次安装，不清楚哪里出错了，目前是看到提示mirai-console started successfully，并可以做一些命令操作

**Comment by SAGIRI-kawaii** [comment]
请查看 [mirai-api-http](https://github.com/project-mirai/mirai-api-http) 关于mcl安装的说明并正确安装

**Comment by RONG-SONG** [comment]
好的，我重新安装

**Comment by RONG-SONG** [comment]
这样应该是成功安装 mirai-api-http，可是界面还是无法加载插件。pycharm 运行提示graia.application.exceptions.InvaildAuthkey，是不是config.yaml中miraiHost端口8080跟MiraiApiHttp中setting.yml保持一致
![图片](https://user-images.githubusercontent.com/48174107/121764285-5ace1700-cb75-11eb-97e0-58ab3d2dff89.png)

**Comment by SAGIRI-kawaii** [comment]
更改authkey为你自己的key并写入config.yaml

**Comment by SAGIRI-kawaii** [comment]
mirai-console-loader-master\config\net.mamoe.mirai-api-http\setting.yml

**Comment by RONG-SONG** [comment]
程序提示graia.application.exceptions.AccountNotFound， 请问你是怎么登录，我登录要求用滑块验证

**Comment by SAGIRI-kawaii** [comment]
那就进行滑块验证后登录，应该有插件

**Comment by RONG-SONG** [comment]
提示说使用这个项目进行自动验证，可是我看这个项目验证方法已经失效了，然后我采用https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88这个进行覆盖device.json，还是失败了，好难搞

![图片](https://user-images.githubusercontent.com/48174107/121765667-23646800-cb7f-11eb-9a75-8a608e93e5c5.png)

**Comment by nullqwertyuiop** [comment]
登录要求验证的话可以试试先用有GUI的系统登录账号，登录完成后把mirai的bot文件夹直接复制过去，我是用这个办法进去的目前

**Comment by RONG-SONG** [comment]
好的，我试试，谢谢

**Comment by nullqwertyuiop** [comment]
无法进行滑动验证码验证的解决方案

请使用 https://github.com/mzdluo123/TxCaptchaHelper
项目来手动完成验证码，必须使用手机

手动完成验证码的方法：
https://github.com/project-mirai/mirai-login-solver-selenium
https://docs.mirai.mamoe.net/mirai-login-solver-selenium/

请注意，必须将手动完成教程里的方式添加 JVM 属性 mirai.slider.captcha.supported (添加参数 -Dmirai.slider.captcha.supported) ，然后将显示的网页url复制到手机完成操作

转发自 https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88

也是可行的记得，之前用vultr的机子登录用的就是这个方法
