### ISSUE TITLE
将 SAGIRIBOT.Handler.Handlers 内文件部分移出后机器人不对部分操作做出回应

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#52]
移出的文件为`BilibiliAppParserHandler.py`，移出后启动时不报错，收到消息时不回应(如图)且不报错。
![2DDB3416-1F2F-44D4-BD77-8BA70DFED2D0](https://user-images.githubusercontent.com/49110142/121793259-ec9a5a80-cc2f-11eb-8961-330a9264c3e9.png)
*特殊情况暂时无法重启bot，所以无法提供更详细的信息。

**Comment by mzttsaintly** [comment]
出现类似问题，在移除LoliconKeywordSearchHandler.py后bot对setting -set 命令无反应且不报错

**Comment by SAGIRI-kawaii** [comment]
已发现问题，将在下次更新修复

**Comment by SAGIRI-kawaii** [comment]
fixed
