### ISSUE TITLE
求一个群每日记事本

### ISSUE THREAD

**Issue by Sirayuki-zh** [SAGIRI-kawaii/sagiri-bot#56]
能手动添加内容
列出当天全部内容
最好再来个计划任务（定时发消息

**Comment by SAGIRI-kawaii** [comment]
qq已经有群日历和群作业这种类似的功能了

**Comment by Sirayuki-zh** [comment]
> qq已经有群日历和群作业这种类似的功能了

那些都要管理员权限添加的吧 而且作业在普通群里有点傻（我的pc端也没这功能
况且我觉得群友不会弄这些（小声

**Comment by SAGIRI-kawaii** [comment]
并入 #86
