### ISSUE TITLE
建议支持同时处理多项工作

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#57]
如题，Sagiri 在处理某项工作时会阻断其他工作正常运行。
如进行耗时较长的幻影/彩色幻影生成时，Sagiri 会阻断后续所有工作，包括接受信息、写入日志、发送色图、自动回复等，直至幻影图片发送完成。

(不看日志一直以为是被系统杀了，然后ps -ef看发现还是一直在运行)

**Comment by SAGIRI-kawaii** [comment]
按理说应该不会的，怪

**Comment by nullqwertyuiop** [comment]
是了，同时建议创建幻影图片前对比两张给出的照片的尺寸，尺寸差异较大的话会整个塞住然后得手动 kill 掉记得.jpg

**Comment by nullqwertyuiop** [comment]
更新：生成幻影图片时给出两张尺寸差异极大的图片，主进程可能会被杀死（占用过多资源？）
环境：Debian Buster

**Comment by nullqwertyuiop** [comment]
找到原因了，是我 vps 配置太低了.jpg

**Comment by SAGIRI-kawaii** [comment]
啊这

**Comment by nullqwertyuiop** [comment]
确实，群消息几十万条()，生成词云会吃很多处理，生成幻影时大了也会卡住()

**Comment by nullqwertyuiop** [comment]
一个能用钱解决的问题(?)
