### ISSUE TITLE
文字转语音的腾讯api是不是老了

### ISSUE THREAD

**Issue by Sirayuki-zh** [SAGIRI-kawaii/sagiri-bot#59]
找了文档说7月1号要关老版本，已经不让注册老版本了

**Comment by nullqwertyuiop** [comment]
同样疑惑，按照腾讯说法，似乎是自 2021 年 7 月 1 日起停止旧有 API 的调用，且目前在腾讯的新控制台中无法找到申请 AppKey 的方法。
不确定停用后会不会对 Sagiri-Bot 的 ChatReply 与 TTS 产生影响，希望是不。

(到现在都没申请到 AppKey，哭了)

**Comment by Sirayuki-zh** [comment]
> 同样疑惑，按照腾讯说法，似乎是自 2021 年 7 月 1 日起停止旧有 API 的调用，且目前在腾讯的新控制台中无法找到申请 AppKey 的方法。
> 不确定停用后会不会对 Sagiri-Bot 的 ChatReply 与 TTS 产生影响，希望是不。
> 
> (到现在都没申请到 AppKey，哭了)

https://cloud.tencent.com/product/tts

**Comment by SAGIRI-kawaii** [comment]
7.1日后再看看，如果不再支持考虑删除功能或寻找替代

**Comment by dh372101** [comment]
https://console.cloud.tencent.com/asr
免费额度：
录音文件识别	每月10小时
一句话识别	每月5000次
实时语音识别	每月5小时
语音流异步识别	每月5小时
录音文件识别极速版	每月5小时

**Comment by nullqwertyuiop** [comment]
7月2日测试，使用现有的 API 会返回 502 错误

**Comment by SAGIRI-kawaii** [comment]
合并到 #62
