### ISSUE TITLE
[Bug]初始化时未读取配置文件

### ISSUE THREAD

**Issue by ForeverOpp** [SAGIRI-kawaii/sagiri-bot#6]
在`sagiri-bot`的第53行开始：
```python
app = GraiaMiraiApplication(
    broadcast=bcc,
    connect_info=Session(
        host="http://localhost:8080",
        authKey="1234567890",
        account=configs["BotQQ"],
        websocket=True
    )
)
```
其中`host`和`authKey`使用默认值，理论上应该从配置文件读取（也有可能后面的代码处理了，我只是跑的时候出错来，推测是这里的问题）

**Comment by SAGIRI-kawaii** [comment]
在此行代码上方应有如下代码：
```python
with open('config.json', 'r', encoding='utf-8') as f:  # 从json读配置
    configs = json.loads(f.read())
```
若没有，请更新至最新版本
另外，请检查 configdemo.json 是否已正确改名为 config.json

**Comment by ForeverOpp** [comment]
> 在此行代码上方应有如下代码：
> 
> ```python
> with open('config.json', 'r', encoding='utf-8') as f:  # 从json读配置
>     configs = json.loads(f.read())
> ```
> 
> 若没有，请更新至最新版本
> 另外，请检查 configdemo.json 是否已正确改名为 config.json

有那个代码，我的意思是您在读取配置文件之后并没有使用，是直接使用的默认值，比如`authKey`这一行应该是`authKey=configs["authKey"]`。

**Comment by SAGIRI-kawaii** [comment]
牙白，疏忽了，在下次push会改正，谢谢指正
