### ISSUE TITLE
智能闲聊api接口的更新

### ISSUE THREAD

**Issue by dh372101** [SAGIRI-kawaii/sagiri-bot#62]
之前也看到别的issue说到7.1就停止原ai接口的使用了，不知道作者有没有意向更新到新的闲聊API接口。
新的接口文档：https://cloud.tencent.com/document/api/271/39416
NLP免费试用：https://console.cloud.tencent.com/nlp2
新接口每个月可以免费调用500000次。

**Comment by SAGIRI-kawaii** [comment]
fixed
