### ISSUE TITLE
权限等级为 4 时可以被自己降权

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#63]
如题，以权限等级 4 的账号发送 `user -grant [at自己] 1/2/3` 时可以对自己降权。同操作对等级为 2/3 的账号无效。
降权后只能手动修改数据库，其他操作无法改回权限等级 4。

**Comment by SAGIRI-kawaii** [comment]
em，怎么有人会想给自己降权（

**Comment by nullqwertyuiop** [comment]
和群里人开玩笑的时候发现的，试了下结果真的可以

众 生 平 等

**Comment by SAGIRI-kawaii** [comment]
只能说不是bug（

**Comment by nullqwertyuiop** [comment]
确实不能算是，执行得很严谨/?

**Comment by SAGIRI-kawaii** [comment]
fixed
