### ISSUE TITLE
权限等级为 4 时可以被其他权限不为 1 的成员降权

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#65]
又是我，我又被改权限了.jpg

如题，以权限等级 2/3 的账号发送 user -grant [at主人号码] 1/2/3 时可以对主人号码降权。
降权后只能手动修改数据库，其他操作无法改回权限等级 4。

怪诶

**Comment by SAGIRI-kawaii** [comment]
fixed
