### ISSUE TITLE
建议支持桌面端添加图片

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#66]
环境: macOS Big Sur 11.4，QQ 6.7.5
复现: `添加setu图片 + [拖入图片]` 并发送
控制台打印的为 `添加setu图片\n[图片]`
使用移动端重复操作，控制台打印的为 `添加setu图片[图片]`
ImageAdderHandler 中未匹配 `\n` 导致不返回预期结果

* 针对从 App Store 或官网获取的 正式版 QQ，Catalyst 版 QQ 及 Windows 版 QQ 未做测试。

**Comment by SAGIRI-kawaii** [comment]
fixed
