### ISSUE TITLE
机器人反撤回的语音无法使用移动端撤回

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#68]
环境: Android 11 ( API 30 ), QQ v8.8.5.5570
该环境下撤回语音条后长按机器人发送的语音条后无撤回选项: 
![EE49C13D4A2B7496E99DB5E848F3D9FF](https://user-images.githubusercontent.com/49110142/124571162-213db280-de7a-11eb-8eef-358f6f701cce.png)

更换环境为: macOS Big Sur 11.4, QQ v6.7.5 后可见撤回选项: 
![CDC4DDD768FDCEB3A692BAC41A717AA0](https://user-images.githubusercontent.com/49110142/124571456-5fd36d00-de7a-11eb-9c2f-26c9f2ceae7d.png)

Windows 环境下未测试

感觉应该写在#53 下面但是发现这个好像算个 bug, 而且只有语音存在这种情况
尝试过删除 MiraiEventHandler.py 中的第252行，使其只发送 revoked_msg, 该问题仍存在

----------日志----------
已开启反撤回的机器人控制台日志显示如下: 
`[BOT (botID)] Group([groupID]) <- '[user]偷偷撤回了自己的一条消息哦：\n\n[mirai:voice:6745E1A34A67F6D3CDCD33**********.amr]'`

另一用于监控机器人的机器人控制台日志显示如下: 
```
[user] 撤回了 自己 的一条消息：\n\n[语音]
[userID]
type='GroupMessage' messageChain=MessageChain((Source(id=6224, time=datetime.datetime(2021, 7, 6, 8, 54, 58, tzinfo=datetime.timezone.utc)), Voice(voiceId='6745E1A34A67F6D3CDCD33**********.amr', url='http://grouptalk.c2c.qq.com/?ver=0&rkey=3062020101045b30590201010201010204bf6128cd0424393050336d61624d5469427544474d70353523456174435a6a5473505067785048486e39020**********41f0000000866696c6574797065000000013100000005636f64656300000001310400&filetype=1&voice_codec=1', path=None, type=<VoiceUploadType.Group: 'group'>))) sender=Member(id=[userID], name='[user]', permission=<MemberPerm.Owner: 'OWNER'>, group=Group(id=[groupID], name='[groupName]', accountPerm=<MemberPerm.Administrator: 'ADMINISTRATOR'>))
```

**Comment by SAGIRI-kawaii** [comment]
之后会修改反撤回代码

**Comment by SAGIRI-kawaii** [comment]
合并到 #53

**Comment by nullqwertyuiop** [comment]
有可能是 mirai 的问题，尝试修改反撤回的提示使其只发送语音时仍无法撤回。
