### ISSUE TITLE
关于机器人的拓展模块的数据库使用问题

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#69]
因为在写一个推送雪球实时新闻单拓展模块，就很好奇使用拓展模块时是否可创建专属于该模块的表单，表单的内容定义在拓展模块中，而不用改动 ORM.py 中的内容。

**Comment by SAGIRI-kawaii** [comment]
目前暂时不行，只能另外建立一个数据库，建议以包的形式编写Saya插件

**Comment by nullqwertyuiop** [comment]
好吧

**Comment by nullqwertyuiop** [comment]
对了，有考虑写 Sagiri-Bot 的开发文档吗()

**Comment by SAGIRI-kawaii** [comment]
也许可以有

**Comment by SAGIRI-kawaii** [comment]
之后闲下来了可能会写一个开发文档.jpg
