### ISSUE TITLE
SAGIRI-BOT 建议反馈处

### ISSUE THREAD

**Issue by SAGIRI-kawaii** [SAGIRI-kawaii/sagiri-bot#7]
球球了，没得写了呜呜呜

**Comment by wingxia** [comment]
啊这，居然会有这么无理的要求，那我就提一个无理的要求！！自定义关键词回复内容（包括图片）！！！

**Comment by SAGIRI-kawaii** [comment]
> 啊这，居然会有这么无理的要求，那我就提一个无理的要求！！自定义关键词回复内容（包括图片）！！！

🉑️，这个之前有在写一直没有写完（就是懒狗）所以一直没有push

**Comment by SAGIRI-kawaii** [comment]
> > 啊这，居然会有这么无理的要求，那我就提一个无理的要求！！自定义关键词回复内容（包括图片）！！！
> 
> 🉑️，这个之前有在写一直没有写完（就是懒狗）所以一直没有push
功能添加完毕，之后会更新文档

**Comment by SAGIRI-kawaii** [comment]
> > 啊这，居然会有这么无理的要求，那我就提一个无理的要求！！自定义关键词回复内容（包括图片）！！！
> 
> 🉑️，这个之前有在写一直没有写完（就是懒狗）所以一直没有push
> 功能添加完毕，之后会更新文档

添加完毕，请前往/docs/functions.md查看使用方法

**Comment by wingxia** [comment]
感谢大佬！

**Comment by MenardiC** [comment]
啊这，居然会有这么无理的要求，那我就提一个无理的要求！！请求增加rss订阅！！！

**Comment by SAGIRI-kawaii** [comment]
> 啊这，居然会有这么无理的要求，那我就提一个无理的要求！！请求增加rss订阅！！！

呜呜呜，可能之后会加上（🕊

**Comment by mangokuma** [comment]
希望支持linux环境，在linux中安装requirements.txt的时候会因为没有wmi导致失败。

**Comment by SAGIRI-kawaii** [comment]
> 希望支持linux环境，在linux中安装requirements.txt的时候会因为没有wmi导致失败。

之后可能会改下，暂时的解决方案可以不装wmi，并注释掉引用wmi的语句

**Comment by SAGIRI-kawaii** [comment]
> 希望支持linux环境，在linux中安装requirements.txt的时候会因为没有wmi导致失败。

项目已重构，新版本目前已支持Windows，Linux以及MacOS环境

**Comment by FROZENJJ** [comment]
可以整一个每日签到获取积分，然后使用功能消耗积分的功能嘛，有些沙雕群滥用严重QAQ

**Comment by SAGIRI-kawaii** [comment]
> 可以整一个每日签到获取积分，然后使用功能消耗积分的功能嘛，有些沙雕群滥用严重QAQ

emmm可以考虑，之后看看（

**Comment by nullqwertyuiop** [comment]
可以做个插件热加载试试？有时候改插件的时候必须要重启 sagiri 才能使改动生效

**Comment by nullqwertyuiop** [comment]
/忘了 注明下使用的环境是python3.8会好些？一开始clone下来跑不起来一直以为是兼容性问题，结果是vultr的debian buster没有python3.8

**Comment by SAGIRI-kawaii** [comment]
> 可以做个插件热加载试试？有时候改插件的时候必须要重启 sagiri 才能使改动生效

可以

**Comment by SAGIRI-kawaii** [comment]
> /忘了 注明下使用的环境是python3.8会好些？一开始clone下来跑不起来一直以为是兼容性问题，结果是vultr的debian buster没有python3.8

之后会在README中声明

**Comment by FROZENJJ** [comment]
想问一下image功能是调用本地图片吗，还是像setu的那个插件一样调用tg的apibot？在代码里貌似没有看到填api的地方

**Comment by FROZENJJ** [comment]
还有是否可以添加一个管理员通过QQ添加图库内容的功能，比如我想上传一张setu的图片，我只需要在聊天框输入相关指令+图片保存到setu地址下

**Comment by SAGIRI-kawaii** [comment]
> 想问一下image功能是调用本地图片吗，还是像setu的那个插件一样调用tg的apibot？在代码里貌似没有看到填api的地方

目前还没有接入api，之后会加入

**Comment by SAGIRI-kawaii** [comment]
> 还有是否可以添加一个管理员通过QQ添加图库内容的功能，比如我想上传一张setu的图片，我只需要在聊天框输入相关指令+图片保存到setu地址下

可以，之后加上

**Comment by SAGIRI-kawaii** [comment]
> 想问一下image功能是调用本地图片吗，还是像setu的那个插件一样调用tg的apibot？在代码里貌似没有看到填api的地方

已添加，请更新最新版本并查看新文档

**Comment by SAGIRI-kawaii** [comment]
> 还有是否可以添加一个管理员通过QQ添加图库内容的功能，比如我想上传一张setu的图片，我只需要在聊天框输入相关指令+图片保存到setu地址下

已添加，请更新最新版本并查看新文档

**Comment by SAGIRI-kawaii** [comment]
若发现bug或者有新功能请求，请单独提出ISSUE，此ISSUE只做建议等反馈用途

**Comment by FROZENJJ** [comment]
可以直接覆盖更新嘛

**Comment by SAGIRI-kawaii** [comment]
> 可以直接覆盖更新嘛

可以，记得更新 `config.yaml` 文件

**Comment by nullqwertyuiop** [comment]
能不能只在被at时对关键词进行回复
比如发送 "@bot 文本" 时进行回复，直接发送 "文本" 时不进行回复

**Comment by SAGIRI-kawaii** [comment]
> 能不能只在被at时对关键词进行回复
> 比如发送 "@bot 文本" 时进行回复，直接发送 "文本" 时不进行回复

🉑️，这样看来还需要改一下数据库结构，可能还需要写一个迁移数据库的程序

**Comment by nullqwertyuiop** [comment]
> > 能不能只在被at时对关键词进行回复
> > 比如发送 "@bot 文本" 时进行回复，直接发送 "文本" 时不进行回复
> 
> 🉑️，这样看来还需要改一下数据库结构，可能还需要写一个迁移数据库的程序

能模糊匹配就更好了.jpg

**Comment by SAGIRI-kawaii** [comment]
> > > 能不能只在被at时对关键词进行回复
> > > 比如发送 "@bot 文本" 时进行回复，直接发送 "文本" 时不进行回复
> > 
> > 
> > 🉑️，这样看来还需要改一下数据库结构，可能还需要写一个迁移数据库的程序
> 
> 能模糊匹配就更好了.jpg

应该可以，请去开一个新的ISSUE并描述清楚请求，我会在之后进行处理

**Comment by Sirayuki-zh** [comment]
求一个记事本  能每天分开来的那种（再加个计划任务

**Comment by RinChan520** [comment]
关键词回复的关键词如果能为正则表达式就好了（

**Comment by icaruszezen** [comment]
请问shadiaoAppName的申请地址是什么？试图找了一下没找到（万分感谢）

**Comment by SAGIRI-kawaii** [comment]
> 请问shadiaoAppName的申请地址是什么？试图找了一下没找到（万分感谢）

我当时好像是发邮件申请的

**Comment by SAGIRI-kawaii** [comment]
> 请问shadiaoAppName的申请地址是什么？试图找了一下没找到（万分感谢）

不过没有应该也没事儿（大概？

**Comment by icaruszezen** [comment]
> > 请问shadiaoAppName的申请地址是什么？试图找了一下没找到（万分感谢）
> 
> 不过没有应该也没事儿（大概？

好像是的，不用申请也能用hh

**Comment by saltfish13** [comment]
等一个B站同步推送动态开播提示的功能整合，参见DDBOT

**Comment by FuYon** [comment]
呜呜呜  从使用到能正常运行  一直报错 修改了好几个.py的源码，对yaml 添加 注释 Loader = yaml.SafeLoader；然后又是数据库的问题  缺少表  但是一开始也不知道怎么用orm指令创建  就硬用IDLE打开py找来找去。 终于是花了很长时间 。踩了很多坑（包括http api版本）才完成了安装。主要这个read me是真的描述的好模糊鸭  希望能改一改。一开始就说mysql跑起来有很多bug得了，我确实一开始配置的也是mysql，然后就一直死循环bug。。换sqlite才好。

**Comment by nullqwertyuiop** [comment]
> 呜呜呜  从使用到能正常运行  一直报错 修改了好几个.py的源码，对yaml 添加 注释 Loader = yaml.SafeLoader；然后又是数据库的问题  缺少表  但是一开始也不知道怎么用orm指令创建  就硬用IDLE打开py找来找去。 终于是花了很长时间 。踩了很多坑（包括http api版本）才完成了安装。主要这个read me是真的描述的好模糊鸭  希望能改一改。一开始就说mysql跑起来有很多bug得了，我确实一开始配置的也是mysql，然后就一直死循环bug。。换sqlite才好。

很怪，我是直接 clone 下来改个 config.yml 就能用了，也是 MySQL，但是 MySQL 用全新数据库存数据就不会报错，有报错可能是改了 AsyncORM.py 然后没有在 MySQL 里面同步更新？
如果是改了 AsyncORM.py 的话报错可能要手动从 MySQL 在对应表里面做对应修改，~~不知道是 bug 还是啥的 alembic 就是不会自动更新 MySQL 的表~~
~~没说改了哪几个文件的源码确实很难对症下药~~

**Comment by SAGIRI-kawaii** [comment]
> 呜呜呜 从使用到能正常运行 一直报错 修改了好几个.py的源码，对yaml 添加 注释 Loader = yaml.SafeLoader；然后又是数据库的问题 缺少表 但是一开始也不知道怎么用orm指令创建 就硬用IDLE打开py找来找去。 终于是花了很长时间 。踩了很多坑（包括http api版本）才完成了安装。主要这个read me是真的描述的好模糊鸭 希望能改一改。一开始就说mysql跑起来有很多bug得了，我确实一开始配置的也是mysql，然后就一直死循环bug。。换sqlite才好。

在README的注意第二条里有写mysql会有许多bug甚至导致无法运行啊，若想稳定运行请使用sqlite。。。
因为我感觉sqlite更轻便一些，在新机器上安装运行也不需要像mysql一样配置环境，所以并没有太考虑对mysql等数据库的适配
至于mirai和mah的版本问题我之后会添加描述

**Comment by nullqwertyuiop** [comment]
SQLite 直接改 AsyncORM 的话 alembic 也会报错（）这样看好像只有我碰上这个问题（？）
-------- 原始信息 --------发件人： ZAPHAKIEL ***@***.***> 日期: 2021/10/31  10:06  (GMT+08:00) 收件人： SAGIRI-kawaii/sagiri-bot ***@***.***> 抄送： Nul ***@***.***>, Comment ***@***.***> 主题： Re: [SAGIRI-kawaii/sagiri-bot] SAGIRI-BOT 建议反馈处 (#7) 

呜呜呜 从使用到能正常运行 一直报错 修改了好几个.py的源码，对yaml 添加 注释 Loader = yaml.SafeLoader；然后又是数据库的问题 缺少表 但是一开始也不知道怎么用orm指令创建 就硬用IDLE打开py找来找去。 终于是花了很长时间 。踩了很多坑（包括http api版本）才完成了安装。主要这个read me是真的描述的好模糊鸭 希望能改一改。一开始就说mysql跑起来有很多bug得了，我确实一开始配置的也是mysql，然后就一直死循环bug。。换sqlite才好。

在README的注意第二条里有写mysql会有许多bug甚至导致无法运行啊，若想稳定运行请使用sqlite。。。
因为我感觉sqlite更轻便一些，在新机器上安装运行也不需要像mysql一样配置环境，所以并没有太考虑对mysql等数据库的适配
至于mirai和mah的版本问题我之后会添加描述
