### ISSUE TITLE
关于我完全不会还非要用这件事

### ISSUE THREAD

**Issue by jiuyouxx** [SAGIRI-kawaii/sagiri-bot#71]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\.env\mcl\main.py", line 15, in <module>
    from WebManager.websocket import set_log
  File "C:\Users\Administrator\Desktop\.env\mcl\WebManager\websocket.py", line 6
, in <module>
    from SAGIRIBOT.utils import get_config
  File "C:\Users\Administrator\Desktop\.env\mcl\SAGIRIBOT\utils.py", line 23, in
 <module>
    from SAGIRIBOT.ORM.AsyncORM import orm
  File "C:\Users\Administrator\Desktop\.env\mcl\SAGIRIBOT\ORM\AsyncORM.py", line
 29, in <module>
    DB_LINK = get_config("DBLink")
  File "C:\Users\Administrator\Desktop\.env\mcl\SAGIRIBOT\ORM\AsyncORM.py", line
 21, in get_config
    with open('config.yaml', 'r', encoding='utf-8') as f:  # 从json读配置
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'

**Comment by nullqwertyuiop** [comment]
把config_demo.yaml复制或者重命名到config.yaml
然后改config.yaml中的配置

**Comment by jiuyouxx** [comment]
已经重命名了

**Comment by nullqwertyuiop** [comment]
先 cd 到项目文件夹再 python3 main.py 试试？

**Comment by nullqwertyuiop** [comment]
已知 Linux 下工作目录不在项目文件夹时直接 python3 main.py 会返回这个错误，Windows 环境下不知道是不是也这样

**Comment by jiuyouxx** [comment]
C:\Users\Administrator>cd C:\Users\Administrator\Desktop\.env\mcl\

C:\Users\Administrator\Desktop\.env\mcl>python3 main.py
'python3' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\Administrator\Desktop\.env\mcl>python main.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\.env\mcl\main.py", line 15, in <module>
    from WebManager.websocket import set_log
  File "C:\Users\Administrator\Desktop\.env\mcl\WebManager\websocket.py", line 6
, in <module>
    from SAGIRIBOT.utils import get_config
  File "C:\Users\Administrator\Desktop\.env\mcl\SAGIRIBOT\utils.py", line 24, in
 <module>
    from SAGIRIBOT.Core.AppCore import AppCore
  File "C:\Users\Administrator\Desktop\.env\mcl\SAGIRIBOT\Core\AppCore.py", line
 8, in <module>
    from graia.saya import Saya
ModuleNotFoundError: No module named 'graia.saya'

**Comment by nullqwertyuiop** [comment]
那就默认你的 python 版本是 3.8 了，不为 3.8 可能会有一些其他问题。
可以使用 `pip install -r [项目目录中的 requirement.txt]` 安装依赖。
如果是单独缺少某个包而 requirement.txt 中没有提及，也可以直接 `pip install [包名]`，如控制台日志中返回 `ModuleNotFoundError: No module named 'graia.saya'` 可以运行 `pip install graia-saya`。
如果安装过程中出现问题( Graia 之类)可以试试使用 `pip install poetry` 然后将 Graia 的仓库克隆下来，cd 进入目录并 `poetry install` 进行安装。

**Comment by jiuyouxx** [comment]
安装完requirements.txt后出现了以下问题
C:\Users\Administrator\Desktop\.env\mcl>python main.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\.env\mcl\main.py", line 8, in <module>
    from graia.application import GraiaMiraiApplication
  File "C:\Users\Administrator\Desktop\.env\python\lib\site-packages\graia\appli
cation\__init__.py", line 14, in <module>
    import graia.application.event.mirai  # for init events
  File "C:\Users\Administrator\Desktop\.env\python\lib\site-packages\graia\appli
cation\event\__init__.py", line 3, in <module>
    from graia.broadcast import BaseEvent
ImportError: cannot import name 'BaseEvent' from 'graia.broadcast' (C:\Users\Adm
inistrator\Desktop\.env\python\lib\site-packages\graia\broadcast\__init__.py)

C:\Users\Administrator\Desktop\.env\mcl>pip install BaseEvent
ERROR: Could not find a version that satisfies the requirement BaseEvent (from v
ersions: none)
ERROR: No matching distribution found for BaseEvent

C:\Users\Administrator\Desktop\.env\mcl>pip install graia.broadcast
Requirement already satisfied: graia.broadcast in c:\users\administrator\desktop
\.env\python\lib\site-packages (0.11.3)

**Comment by nullqwertyuiop** [comment]
怪，没碰到过这个问题，如果是 Graia.Broadcast 的问题的话应该在 https://github.com/GraiaProject/BroadcastControl 开 issue

**Comment by jiuyouxx** [comment]
我python是3.9.2版本的，会和这个有关吗

**Comment by nullqwertyuiop** [comment]
不知道，我 Debian 用 Python3.9 的会有问题

**Comment by jiuyouxx** [comment]
那我换个版本试试

**Comment by jiuyouxx** [comment]
换了个版本又变成这样了
C:\Users\Administrator>C:\Users\Administrator\Desktop\.env\mcl\main.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\.env\mcl\main.py", line 8, in <module>
    from graia.application import GraiaMiraiApplication
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\graia\application\__init__.py", line 18, in <module>
    from graia.application.event.lifecycle import (  # for init lifecycle events

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\graia\application\event\lifecycle.py", line 3, in <module>
    from graia.broadcast.entities.event import Dispatchable, BaseDispatcher
ImportError: cannot import name 'BaseDispatcher' from 'graia.broadcast.entities.
event' (C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\graia\broadcast\entities\event.py)

**Comment by SAGIRI-kawaii** [comment]
尝试使用 graia-application-mirai 0.19.2

**Comment by jiuyouxx** [comment]
ERROR: pip's dependency resolver does not currently take into account all the pa
ckages that are installed. This behaviour is the source of the following depende
ncy conflicts.
graia-application-mirai 0.19.2 requires graia-broadcast<0.9.0,>=0.8.0, but you h
ave graia-broadcast 0.11.3 which is incompatible.

**Comment by jiuyouxx** [comment]
ERROR: pip's dependency resolver does not currently take into account all the pa
ckages that are installed. This behaviour is the source of the following depende
ncy conflicts.
graia-scheduler 0.0.5 requires graia-broadcast<0.12.0,>=0.11.1, but you have gra
ia-broadcast 0.8.0 which is incompatible.

**Comment by SAGIRI-kawaii** [comment]
升级graia-broadcast

**Comment by jiuyouxx** [comment]
这上下两个一个需要高版本一个需要低版本，我不知道咋办了

**Comment by jiuyouxx** [comment]
换一次版本报个不同的错

**Comment by jiuyouxx** [comment]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\.env\mcl\main.py", line 8, in <module>
    from graia.application import GraiaMiraiApplication
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\graia\application\__init__.py", line 14, in <module>
    import graia.application.event.mirai  # for init events
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\graia\application\event\__init__.py", line 3, in <module>
    from graia.broadcast import BaseEvent
ImportError: cannot import name 'BaseEvent' from 'graia.broadcast' (C:\Users\Adm
inistrator\AppData\Local\Programs\Python\Python38\lib\site-packages\graia\broadc
ast\__init__.py)

**Comment by SAGIRI-kawaii** [comment]
全部卸载后重新安装

**Comment by jiuyouxx** [comment]
重装完又换了一个
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\.env\mcl\main.py", line 8, in <module>
    from graia.application import GraiaMiraiApplication
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\graia\application\__init__.py", line 18, in <module>
    from graia.application.event.lifecycle import (  # for init lifecycle events

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\graia\application\event\lifecycle.py", line 3, in <module>
    from graia.broadcast.entities.event import Dispatchable, BaseDispatcher
ImportError: cannot import name 'BaseDispatcher' from 'graia.broadcast.entities.
event' (C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\graia\broadcast\entities\event.py)

**Comment by SAGIRI-kawaii** [comment]
pip install -U graia-application-mirai==0.19.2

**Comment by jiuyouxx** [comment]
可以用啦，感谢大佬
