### ISSUE TITLE
机器人不对 MemberCardChangeEvent 做出回应

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#72]
看了下 `SAGIRIBOT.Handler.Handlers.MiraiEventHandler` 的内容，第 189 行至第 198 行应该是机器人对 MemberCardChangeEvent 的反应，但是实际测试时机器人对该事件不做出回应。

Mirai 控制台日志如下：
`2021-07-13 01:45:15 V/Bot.[BOTID]: Event: MemberCardChangeEvent(origin=<LTR>, new=<LTR>测试机器人, member=NormalMember([UID]))`

**Comment by SAGIRI-kawaii** [comment]
我这里好像可以（

**Comment by nullqwertyuiop** [comment]
很怪，mirai 登录协议用的是 android_pad，不知道是不是和这个有关系？

**Comment by SAGIRI-kawaii** [comment]
既然有log应该不会？我也是PAD协议，试下PHONE？

**Comment by nullqwertyuiop** [comment]
换了 phone 协议也是一样，可能和 graia 版本有关？

**Comment by SAGIRI-kawaii** [comment]
没有吧应该？

**Comment by nullqwertyuiop** [comment]
怪，graia换了 0.19.2 也无反应

**Comment by SAGIRI-kawaii** [comment]
记得更新（我之前release发现少push个文件
要是我改了数据库结构就会报错的（

**Comment by nullqwertyuiop** [comment]
有反应，但是是报错( 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/__init__.py", line 186, in Executor
    ] = await dii.lookup_param_without_log(
  File "/usr/local/lib/python3.8/site-packages/graia/broadcast/interfaces/dispatcher.py", line 267, in lookup_param_without_log
    raise RequirementCrashed(
graia.broadcast.exceptions.RequirementCrashed: ('the dispatching requirement crashed: ', 'group', <class 'graia.application.group.Group'>, None)
```

**Comment by nullqwertyuiop** [comment]
umm...可能是我 graia-broadcast 版本太高了？刚 list 看了下是 0.11.3

**Comment by nullqwertyuiop** [comment]
降到了兼容 graia-application-mirai==0.19.2 的 graia-broadcast==0.8.0 也是报类似的错误(

**Comment by SAGIRI-kawaii** [comment]
还有什么头猪吗（

**Comment by nullqwertyuiop** [comment]
会是mirai-core版本的问题吗(
我的是2.6-M2
