### ISSUE TITLE
指令问题

### ISSUE THREAD

**Issue by jiuyouxx** [SAGIRI-kawaii/sagiri-bot#73]
设定好的关键词在哪设定呀

**Comment by nullqwertyuiop** [comment]
添加功能关键词#功能#关键词

应该是这样

**Comment by jiuyouxx** [comment]
机器人回复非法方法名

**Comment by YuiKira** [comment]
那请问下speak_mode可以设置关键词吗, 添加功能关键词#speak_mode#关键词这样会报非法

**Comment by SAGIRI-kawaii** [comment]
不可以，添加功能关键词仅为图片发送功能内置，合法功能名如下
"setu", "real", "realHighq", "bizhi", "sketch"

**Comment by YuiKira** [comment]
> 不可以，添加功能关键词仅为图片发送功能内置，合法功能名如下
> "setu", "real", "realHighq", "bizhi", "sketch"

好的,谢谢~
