### ISSUE TITLE
import导入问题

### ISSUE THREAD

**Issue by YuiKira** [SAGIRI-kawaii/sagiri-bot#74]
python 3.9 ;requirements已经装过了,麻烦请教一下如何解决
错误代码:
File "C:\Users\Administrator\Desktop\sagiri-bot-2.1.5\main.py", line 8, in <module>
    from graia.application import GraiaMiraiApplication
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\graia\application\__init__.py", line 18, in <module>
    from graia.application.event.lifecycle import (  # for init lifecycle events
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\graia\application\event\lifecycle.py", line 3, in <module>
    from graia.broadcast.entities.event import Dispatchable, BaseDispatcher
ImportError: cannot import name 'BaseDispatcher' from 'graia.broadcast.entities.event' (C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\graia\broadcast\entities\event.py)

**Comment by SAGIRI-kawaii** [comment]
pip install -U grain-application-mirai==0.19.2

**Comment by kokorousaki** [comment]
> pip install -U graia-application-mirai==0.19.2

![image](https://user-images.githubusercontent.com/87707351/129525047-e1888709-7fb6-4513-bf75-abc50cfb4cf1.png)
![image](https://user-images.githubusercontent.com/87707351/129525061-989ed43d-5c41-40cc-a18b-8eeeebd106db.png)
反复套娃。。。。

**Comment by kokorousaki** [comment]
![image](https://user-images.githubusercontent.com/87707351/129526634-da4f661b-9c43-4a97-b750-1cbd6232c291.png)
换成0.0.8版本后解决了，出现新的问题

**Comment by SAGIRI-kawaii** [comment]
mah1.x

**Comment by Evyde** [comment]
没想到2022年还能遇到这个问题。
解决办法：
重建Python虚拟环境，重装requirements

**Comment by nullqwertyuiop** [comment]
？怎么这个issue还有人挖出来

**Comment by Evyde** [comment]
> ？怎么这个issue还有人挖出来

草您好快的回
很简单，Google报错信息第一个：
<img width="731" alt="image" src="https://user-images.githubusercontent.com/9302540/200028270-e3314a89-8f4c-4ad5-b0f2-ca4bd1169977.png">
