### ISSUE TITLE
关于我启动后报错看不懂但还想用这件事（

### ISSUE THREAD

**Issue by GayFunny233** [SAGIRI-kawaii/sagiri-bot#79]
这里显示如图，graia-application-mirai是0.19.2，broadcast是0.8.11，python3.8.10
![image](https://user-images.githubusercontent.com/39610941/126062352-3356f38a-33d6-4951-a85a-bc149357a4a7.png)

**Comment by SAGIRI-kawaii** [comment]
初始化有一段时间，启动后过一会儿再使用功能应该就不会出现此问题

**Comment by GayFunny233** [comment]
已经挂在服务器上面3天了，仍会有这样子的情况，而且只是部分功能用不了（目前已知x日内新番，月内总结，历史上的今天，xx热搜，ph 5000兆 u2图片生成）
![image](https://user-images.githubusercontent.com/39610941/126727759-54c05f57-0b33-4720-ad5e-eb2b3da784d9.png)

**Comment by SAGIRI-kawaii** [comment]
尝试重启后再试下有吗？

**Comment by GayFunny233** [comment]
昨天重启了一下，特地等了一天才回复，结果还是这样子

**Comment by GayFunny233** [comment]
可以麻烦您发一下您用的各种模块的版本吗，我换个版本试试看

**Comment by SAGIRI-kawaii** [comment]
代码是最新版嘛

**Comment by GayFunny233** [comment]
是的，2.1.5

**Comment by SAGIRI-kawaii** [comment]
emmmm我也不太清楚？按理说不会出现这种问题呢，启动时有报错吗

**Comment by GayFunny233** [comment]
没有，启动正常，那个web管理器也显示加载加载70几个Handler和10几个saya（具体忘了），有没有可能是我用的模块版本和您的不一样导致的？

**Comment by SAGIRI-kawaii** [comment]
不太可能？尝试下2.1.6？
