### ISSUE TITLE
任何权限成员都可申请生成本群词云

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#84]
与功能描述不符合.jpg

**Comment by SAGIRI-kawaii** [comment]
是最新版嘛

**Comment by nullqwertyuiop** [comment]
是的

发送自 Windows 10 版邮件应用

发件人: ZAPHAKIEL
发送时间: 2021年7月26日 18:41
收件人: SAGIRI-kawaii/sagiri-bot
抄送: nullqwertyuiop; Author
主题: Re: [SAGIRI-kawaii/sagiri-bot] 任何权限成员都可申请生成本群词云 (#84)

是最新版嘛

**Comment by nullqwertyuiop** [comment]
怪，克隆过来的代码上看确实也是权限 2 级以上才能生成，运行起来就无视权限了

**Comment by SAGIRI-kawaii** [comment]
本地测试并未遇到此问题，查看申请人权限是否为1

**Comment by nullqwertyuiop** [comment]
怪
![Screenshot_20210727-192613_QQ.jpg](https://user-images.githubusercontent.com/49110142/127146147-1a9ef1e7-b682-4d75-b108-e8ad6012af8f.jpg)

**Comment by SAGIRI-kawaii** [comment]
怪

**Comment by SAGIRI-kawaii** [comment]
有什么思路吗

**Comment by nullqwertyuiop** [comment]
傻了，我以为我把新合并的 handler 传服务器上了，结果服务器上老的 handler 没有检查权限这一步
我的锅（
