### ISSUE TITLE
覆盖更新时数据库报错

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#85]
数据库: MySQL (数据库结构由 `SAGIRI-BOT v2.1.3` 创建)
更新至 v2.1.6 后直接运行报错，手动在表 `setting` 的 `long_text_type` 列后添加 `dice` 和 `anti_flashimage` 列后可正常运行。

**Comment by SAGIRI-kawaii** [comment]
是否有更新依赖，安装alembic？

**Comment by nullqwertyuiop** [comment]
？有新的依赖吗，忘了这茬儿
-------- 原始信息 --------发件人： ZAPHAKIEL ***@***.***> 日期: 2021/7/27  17:27  (GMT+08:00) 收件人： SAGIRI-kawaii/sagiri-bot ***@***.***> 抄送： nullqwertyuiop ***@***.***>, Author ***@***.***> 主题： Re: [SAGIRI-kawaii/sagiri-bot] 覆盖更新时数据库报错 (#85) 

是否有更新依赖，安装alembic？
