### ISSUE TITLE
switch 为 False 时机器人仍进行复读

### ISSUE THREAD

**Issue by nullqwertyuiop** [SAGIRI-kawaii/sagiri-bot#93]
如图，机器人版本为最新一次 commit
![-1ba3d1b97b5d8c9d.png](https://user-images.githubusercontent.com/49110142/127739199-3db1e15e-7841-4e29-a69e-fb6865c5f823.png)

**Comment by SAGIRI-kawaii** [comment]
因为switch不对管理员进行限制

**Comment by nullqwertyuiop** [comment]
？这样的吗

**Comment by SAGIRI-kawaii** [comment]
也可以改成有限制的，保留command_parse模块功能
