### ISSUE TITLE
[求助]saya应该怎么写GraiaScheduler呀,没有找到相关示例

### ISSUE THREAD

**Issue by Last-ID** [SAGIRI-kawaii/sagiri-bot#97]
相关模块：[Broadcast Control for Graia Framework](https://github.com/GraiaProject/Scheduler)
或者，有没有其他可以实现定时任务的办法

**Comment by nullqwertyuiop** [comment]
这个感觉应该在graia那里开issue吧.jpg

**Comment by Last-ID** [comment]
qwq...直接用graia创建定时任务有给示例(如下)，但是不知道应该如何用saya插件的形式实现
```
import asyncio
from graia.broadcast import Broadcast
from graia.scheduler import GraiaScheduler
from graia.scheduler.timers import crontabify

loop = asyncio.get_event_loop()

bcc = Broadcast(loop=loop, debug_flag=True)
scheduler = GraiaScheduler(
    loop, bcc
)

@scheduler.schedule(crontabify("* * * * * *"))
def something_scheduled():
    print("print every seconds.")

loop.run_forever()

```

**Comment by SAGIRI-kawaii** [comment]
@channel.use(SchedulerSchema(crontabify("0 5 * * *)))
async def func(): ...

**Comment by Last-ID** [comment]
> @channel.use(_**SchedulerSchema**_(crontabify("0 5 * * *")))

—————————^^^^^^

> async def func(): ...

此处SchedulerSchema应该用啥方法导入呀

> from graia.saya.builtins.broadcast.schema import ListenerSchema

没有找到相关的库



> 
> 
> @channel.use(SchedulerSchema(crontabify("0 5 * * *)))
> async def func(): ...

**Comment by SAGIRI-kawaii** [comment]
from graia.scheduler.saya.schema import SchedulerSchema

**Comment by Last-ID** [comment]
### 完整代码
```python
from graia.application import GraiaMiraiApplication
from graia.application.message.elements.internal import Plain
from graia.application.message.elements.internal import Image
from graia.saya import Saya, Channel
from graia.saya.builtins.broadcast.schema import ListenerSchema
from graia.application.event.messages import *
from graia.application.exceptions import AccountMuted

from graia.scheduler import GraiaScheduler
from graia.scheduler.timers import crontabify
from graia.scheduler.saya.schema import SchedulerSchema

# 插件信息
__name__ = "Rsc_Clear"
__description__ = "用以每日重置"
__author__ = "Last_ID(Github:last-id)"
__usage__ = ""

saya = Saya.current()
channel = Channel.current()

channel.name(__name__)
channel.description(f"{__description__}\n使用方法：{__usage__}")
channel.author(__author__)


@channel.use(SchedulerSchema(crontabify("0/20 * * * *")))
async def rsc_clear(app: GraiaMiraiApplication, message: MessageChain, group: Group, sender: Member):
    print("Hi~")
    await app.sendGroupMessage(group, MessageChain.create([Plain("Hi~")]))
```



### 版本信息
graia-application-mirai==0.19.2
graia-broadcast==0.8.11
graia-saya==0.0.9
graia-scheduler==0.0.4
### 输出报错
> 
> PS C:\saya_plugins_collection-master> & G:/Python/Python39/python.exe c:/saya_plugins_collection-master/main.py
> 2021-08-03 19:00:25.927 | DEBUG    | graia.saya:require:107 - require modules.Rsc_Clear
> 2021-08-03 19:00:26.002 | ERROR    | graia.saya:require_resolve:81 - an error occurred while loading the module's cube: modules.Rsc_Clear::Cube(content=<function rsc_clear at 0x000001CB3B895B80>, metaclass=SchedulerSchema(timer=<generator object crontabify at 0x000001CB3B82A900>, cancelable=False, decorators=[], dispatchers=[], enableInternalAccess=False))
> Traceback (most recent call last):
> 
>   File "c:\saya_plugins_collection-master\main.py", line 39, in <module>
>     saya.require(f"modules.{module.split('.')[0]}")
>     │    └ <function Saya.require at 0x000001CB3A81AA60>
>     └ <graia.saya.Saya object at 0x000001CB3B779A60>
> 
>   File "G:\Python\Python39\lib\site-packages\graia\saya\__init__.py", line 116, in require
>     channel = self.require_resolve(module)
>               │    │               └ 'modules.Rsc_Clear'
>               │    └ <function Saya.require_resolve at 0x000001CB3A81A940>
>               └ <graia.saya.Saya object at 0x000001CB3B779A60>
> 
> > File "G:\Python\Python39\lib\site-packages\graia\saya\__init__.py", line 79, in require_resolve
>     interface.allocate_cube(cube)
>     │         │             └ Cube(content=<function rsc_clear at 0x000001CB3B895B80>, metaclass=SchedulerSchema(timer=<generator object crontabify at 0x00...
>     │         └ <function BehaviourInterface.allocate_cube at 0x000001CB3A2EB940>
>     └ <graia.saya.behaviour.interface.BehaviourInterface object at 0x000001CB3B785100>
> 
>   File "G:\Python\Python39\lib\site-packages\graia\saya\behaviour\interface.py", line 64, in allocate_cube
>     raise RequirementCrashed(
>           └ <class 'graia.broadcast.exceptions.RequirementCrashed'>
> 
> graia.broadcast.exceptions.RequirementCrashed: the dispatching requirement crashed: Cube(content=<function rsc_clear at 0x000001CB3B895B80>, metaclass=SchedulerSchema(timer=<generator object crontabify at 0x000001CB3B82A900>, cancelable=False, decorators=[], dispatchers=[], enableInternalAccess=False))
> Traceback (most recent call last):
>   File "c:\saya_plugins_collection-master\main.py", line 39, in <module>
>     saya.require(f"modules.{module.split('.')[0]}")
>   File "G:\Python\Python39\lib\site-packages\graia\saya\__init__.py", line 116, in require
>     channel = self.require_resolve(module)
>   File "G:\Python\Python39\lib\site-packages\graia\saya\__init__.py", line 82, in require_resolve
>     raise
>   File "G:\Python\Python39\lib\site-packages\graia\saya\behaviour\interface.py", line 42, in __exit__
>     raise exc.with_traceback(tb)
>   File "G:\Python\Python39\lib\site-packages\graia\saya\__init__.py", line 79, in require_resolve
>     interface.allocate_cube(cube)
>   File "G:\Python\Python39\lib\site-packages\graia\saya\behaviour\interface.py", line 64, in allocate_cube
>     raise RequirementCrashed(
> graia.broadcast.exceptions.RequirementCrashed: the dispatching requirement crashed: Cube(content=<function rsc_clear at 0x000001CB3B895B80>, metaclass=SchedulerSchema(timer=<generator object crontabify at 0x000001CB3B82A900>, cancelable=False, decorators=[], dispatchers=[], enableInternalAccess=False))

_琢磨了许久，一点也没看懂)_

**Comment by I-love-study** [comment]
根据Saya的规范，你需要安装behaviour
你可以在main.py增加以下代码:
```python
from graia.scheduler import GraiaScheduler
from graia.scheduler.saya import GraiaSchedulerBehaviour
sche = GraiaScheduler(loop = loop, broadcast = bcc)
saya.install_behaviours(GraiaSchedulerBehaviour(sche))
```
这样就能在模组里使用`SchedulerSchema`了

@SAGIRI-kawaii 
#98 应该可以自动安装GraiaSchedulerBehaviour(大概)

**Comment by SAGIRI-kawaii** [comment]
确实
