### ISSUE TITLE
安装依赖时报错

### ISSUE THREAD

**Issue by Wdam** [SAGIRI-kawaii/sagiri-bot#99]
![image](https://user-images.githubusercontent.com/42366809/128462646-23355f20-8d9e-4bc8-ab7b-684040b54550.png)

**Comment by SAGIRI-kawaii** [comment]
请前往 [graiax-silkcoder](https://github.com/I-love-study/graiax-silkcoder) 处提交ISSUE
或尝试安装指定版本 `pip install -U graiax-silkcoder==0.0.8`

**Comment by Wdam** [comment]
已经尝试过
python版本
![image](https://user-images.githubusercontent.com/42366809/128466672-d3ded11b-be70-477d-b954-b0462ad9bcea.png)
![image](https://user-images.githubusercontent.com/42366809/128466763-60858eeb-b88f-45c0-9c7e-2930ce655c1b.png)
![image](https://user-images.githubusercontent.com/42366809/128466803-18ee0322-a242-423c-b70d-c0fba66d2938.png)
